/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.43
 * Generated at: 2021-01-07 23:39:38 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import user.model.vo.User;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/./views/common/footer.jsp", Long.valueOf(1610060554004L));
    _jspx_dependants.put("/./views/common/header.jsp", Long.valueOf(1610060468650L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("user.model.vo.User");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			"./views/common/error.jsp", true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>직산 가정의학과 의원</title>\r\n");
      out.write("<script type = \"text/javascript\" src = \"/jiksan/resources/js/jquery-3.5.1.min.js\"></script>\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=no, target-densitydpi=medium-dpi\">\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"/jiksan/resources/css/main_slick.css\"/>\t\t");
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/jiksan/resources/css/main_bootstrap.min.css\"/>\t\t");
      out.write("\r\n");
      out.write("<link href=\"/jiksan/resources/css/main_reset.css\" rel=\"stylesheet\" type=\"text/css\" />\t\t");
      out.write("\r\n");
      out.write("<link href=\"/jiksan/resources/css/main_common.css\" rel=\"stylesheet\" type=\"text/css\" />\t\t");
      out.write("\r\n");
      out.write("<link href=\"/jiksan/resources/css/main_main.css\" rel=\"stylesheet\" type=\"text/css\" />\t\t");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/JavaScript\" src=\"/jiksan/resources/js/slick.js\"></script>\r\n");
      out.write("<script type=\"text/JavaScript\" src=\"/jiksan/resources/js/script.js\"></script>\r\n");
      out.write(" <script type=\"text/javascript\" src=\"/jiksan/resources/js/link.js\"></script>\r\n");
      out.write("<script src=\"/jiksan/resources/js/script-functions.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"/jiksan/resources/js/EmbedFlash.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<style type = \"text/css\">\r\n");
      out.write(".main .homepage .slideshow{position:relative}\r\n");
      out.write("\r\n");
      out.write(".slideshowPics {display:none}\r\n");
      out.write(".w3-left, .w3-right, .w3-badge {cursor:pointer}\r\n");
      out.write(".w3-badge {height:13px;width:13px;padding:0}\r\n");
      out.write(".w3-content {margin-left:auto;margin-right:auto; /* max-width:980px; */}\r\n");
      out.write(".w3-display-container{position:relative;}\r\n");
      out.write("/*\r\n");
      out.write(".w3-display-container:hover .w3-display-hover{display:block;}\r\n");
      out.write(".w3-display-container:hover span.w3-display-hover{display:inline-block;}\r\n");
      out.write("*/\r\n");
      out.write(".w3-center {text-align:center!important}\r\n");
      out.write(".w3-container:after,.w3-container:before {content:\"\";display:table;clear:both;}\r\n");
      out.write(".w3-container {padding:0.01em 16px;}\r\n");
      out.write(".w3-section {margin-top:16px!important;margin-bottom:16px!important}\r\n");
      out.write(".w3-large {font-size:25px!important}\r\n");
      out.write(".w3-text-white {color:#265277!important}\r\n");
      out.write(".w3-display-bottommiddle{position:absolute;left:50%;bottom:0;transform:translate(-50%,0%);-ms-transform:translate(-50%,0%)}\r\n");
      out.write(".w3-left{float:left!important}\r\n");
      out.write(".w3-right{float:right!important}\r\n");
      out.write(".w3-hover-text-khaki:hover{color:#b4aa50!important}\r\n");
      out.write("/* .w3-badge{border-radius:50%;background-color:#000;color:#265277;display:inline-block;padding-left:8px;padding-right:8px;text-align:center}\r\n");
      out.write(".w3-border{border:1px solid rgba(38, 82, 119, 0.6)!important}\r\n");
      out.write(".w3-transparent {background-color:transparent!important}\r\n");
      out.write(".w3-hover-white:hover{color:#000!important;background-color:rgba(38, 82, 119, 0.6)!important} */\r\n");
      out.write("\r\n");
      out.write("table#newnotice, #newnotice >tr, #newnotice >th {\r\n");
      out.write("position: relative;\r\n");
      out.write("width: auto;\r\n");
      out.write("min-width: 600px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<!-- 예약페이지로 넘어가게하는 함수 -->\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("        function redirect(){\r\n");
      out.write("        window.location.href = \"/jiksan/drlist\"\r\n");
      out.write("        }\r\n");
      out.write("        function redirectAdmin(){\r\n");
      out.write("        window.location.href = \"/jiksan/drlist.ad\"\r\n");
      out.write("        }\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write('\r');
      out.write('\n');
   User loginUser = (User)session.getAttribute("loginUser"); 
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\"    href=\"/jiksan/resources/css/jiksan-header.css\" />\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("   src=\"/jiksan/resources/js/jquery-3.5.1.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("$(document).ready(function(){\r\n");
      out.write("   $(\".full-slide\").click(function() {\r\n");
      out.write("      $(\".full-menu\").stop().slideToggle(300);\r\n");
      out.write("         $('.hamburger .line').css('transition', 'all 0.2s ease-in-out');\r\n");
      out.write("\r\n");
      out.write("         if($('.hamburger').hasClass('is-active')){\r\n");
      out.write("            $('.hamburger span:nth-child(1)').css({'transform':'translateY(0) rotate(0)'});\r\n");
      out.write("            $('.hamburger span:nth-child(2)').css({'opacity':'1'});\r\n");
      out.write("            $('.hamburger span:nth-child(3)').css({'transform':'translateY(0) rotate(0)'});            \r\n");
      out.write("            $('.hamburger').removeClass('is-active');\r\n");
      out.write("         } else {\r\n");
      out.write("            $('.hamburger span:nth-child(1)').css({'transform':'translateY(12px) rotate(45deg)'});\r\n");
      out.write("            $('.hamburger span:nth-child(2)').css({'opacity':'0'});\r\n");
      out.write("            $('.hamburger span:nth-child(3)').css({'transform':'translateY(-4px) rotate(-45deg)'});\r\n");
      out.write("            $('.hamburger').addClass('is-active');\r\n");
      out.write("         }\r\n");
      out.write("    });\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("   function setCookie(name, value, expiredays) {\r\n");
      out.write("      var todayDate = new Date();\r\n");
      out.write("      todayDate.setDate(todayDate.getDate() + expiredays);\r\n");
      out.write("      document.cookie = name + \"=\" + escape(value) + \"; path=/; expires=\" + todayDate.toGMTString() + \";\"\r\n");
      out.write("   }\r\n");
      out.write("   function getCookie(name) {\r\n");
      out.write("      var nameOfCookie = name + \"=\";\r\n");
      out.write("      var x = 0;\r\n");
      out.write("      while (x <= document.cookie.length) {\r\n");
      out.write("         var y = (x + nameOfCookie.length);\r\n");
      out.write("         if (document.cookie.substring(x, y) == nameOfCookie) {\r\n");
      out.write("            if ((endOfCookie = document.cookie.indexOf(\";\", y)) == -1)\r\n");
      out.write("               endOfCookie = document.cookie.length;\r\n");
      out.write("            return unescape(document.cookie.substring(y, endOfCookie));\r\n");
      out.write("         }\r\n");
      out.write("         x = document.cookie.indexOf(\" \", x) + 1;\r\n");
      out.write("         if (x == 0)\r\n");
      out.write("            break;\r\n");
      out.write("      }\r\n");
      out.write("      return \"\";\r\n");
      out.write("   }\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("        function redirect(){\r\n");
      out.write("        window.location.href = \"/jiksan/drlist\"\r\n");
      out.write("        }\r\n");
      out.write("        function redirectAdmin(){\r\n");
      out.write("        window.location.href = \"/jiksan/drlist.ad\"\r\n");
      out.write("        }\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("   <div id=\"wrap\" class=\"mw1600\" style=\"position: relative;\">\r\n");
      out.write("      <div class=\"mw1600\">\r\n");
      out.write("         <header class=\"bg-white mw\">\r\n");
      out.write("            <div id=\"header-wrap\" class=\"inner cf\">\r\n");
      out.write("               <a href=\"/jiksan/index.jsp\"><img\r\n");
      out.write("                  src=\"/jiksan/resources/main_images/jiksan_logo.png\"\r\n");
      out.write("                  alt=\"직산 가정의학과 의원\" style=\"width: auto; max-width: 22%\"></a>\r\n");
      out.write("\r\n");
      out.write("               <section>\r\n");
      out.write("                  ");
      out.write("\r\n");
      out.write("                  ");
 if(loginUser == null){ 
      out.write("\r\n");
      out.write("                  <nav>\r\n");
      out.write("                     <a href=/jiksan/views/user/userLogin.jsp><img\r\n");
      out.write("                        src=\"/jiksan/resources/main_images/nav-icon01.png\" alt=\"LOGIN\"><span>LOGIN</span></a>\r\n");
      out.write("                     <a href=\"/jiksan/views/user/userEnroll.jsp\"><img\r\n");
      out.write("                        src=\"/jiksan/resources/main_images/nav-icon02.png\" alt=\"JOIN\"><span>JOIN</span></a>\r\n");
      out.write("                     <a href=\"/jiksan/views/about/contact-us.jsp\"><img\r\n");
      out.write("                        src=\"/jiksan/resources/main_images/nav-icon03.png\"\r\n");
      out.write("                        alt=\"CONTACT US\"><span>CONTACT US</span></a> <a href=\"#n\"\r\n");
      out.write("                        class=\"full-slide\">\r\n");
      out.write("                        <div class=\"row\">\r\n");
      out.write("                           <div class=\"three col\">\r\n");
      out.write("                              <div class=\"hamburger\" id=\"hamburger-1\">\r\n");
      out.write("                                 <span class=\"line\"></span> <span class=\"line\"></span> <span\r\n");
      out.write("                                    class=\"line\"></span>\r\n");
      out.write("                              </div>\r\n");
      out.write("                           </div>\r\n");
      out.write("                        </div> <span style=\"font-weight: 500; color: #74afc9;\">전체메뉴</span>\r\n");
      out.write("                     </a>\r\n");
      out.write("                  </nav>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"full-menu bg-white\">\r\n");
      out.write("               <div class=\"inner\">\r\n");
      out.write("                  <ul class=\"full-list inner cf\">\r\n");
      out.write("                     <li>\r\n");
      out.write("                        <div>병원안내</div>\r\n");
      out.write("                        <ol>\r\n");
      out.write("                           <li><a href=\"/jiksan/views/about/about-clinic.jsp\">병원안내</a></li>\r\n");
      out.write("                           <li><a href=\"/jiksan/views/about/about-services.jsp\">진료안내</a></li>\r\n");
      out.write("                           <li><a href=\"/jiksan/views/about/about-team.jsp\">의료진 소개</a></li>\r\n");
      out.write("                           <li><a href=\"/jiksan/views/about/contact-us.jsp\">오시는길</a></li>\r\n");
      out.write("                        </ol>\r\n");
      out.write("                     </li>\r\n");
      out.write("                     <li>\r\n");
      out.write("                        <div>당뇨클리닉</div>\r\n");
      out.write("                        <ol>\r\n");
      out.write("                           <li><a href=\"/jiksan/disease?disease_no=108\">당뇨병이란?</a></li>\r\n");
      out.write("                           <li><a href=\"/jiksan/views/diabetes/diabetes-diet.jsp\">당뇨병과 식생활</a></li>\r\n");
      out.write("                           <li><a href=\"/jiksan/views/diabetes/diabetes-exercise.jsp\">당뇨병과 운동</a></li>\r\n");
      out.write("                           <li><a href=\"/jiksan/disease?disease_no=108#complications\">당뇨병 합병증</a></li>\r\n");
      out.write("                        </ol>\r\n");
      out.write("                     </li>\r\n");
      out.write("                     <li>\r\n");
      out.write("                        <div>건강정보</div>\r\n");
      out.write("                        <ol>\r\n");
      out.write("                           <li><a href=\"/jiksan/dlist\">질환백과</a></li>\r\n");
      out.write("                           ");
      out.write("\r\n");
      out.write("                        </ol>\r\n");
      out.write("                     </li>\r\n");
      out.write("                     <li>\r\n");
      out.write("                        <div>진료 예약</div>\r\n");
      out.write("                        <ol>\r\n");
      out.write("                           <li><a href=\"/jiksan/views/reservation/about-appt.jsp\">예약안내</a></li>\r\n");
      out.write("                           <li><a href=\"javascript:redirect()\">진료 예약하기</a></li>\r\n");
      out.write("                           ");
      out.write("\r\n");
      out.write("                        </ol>\r\n");
      out.write("                     </li>\r\n");
      out.write("                     <li>\r\n");
      out.write("                        <div>커뮤니티</div>\r\n");
      out.write("                        <ol>\r\n");
      out.write("                           <li><a href=\"/jiksan/nlist\">공지사항</a></li>\r\n");
      out.write("                           <li><a href=\"/jiksan/faqlist\">자주묻는 질문</a></li>\r\n");
      out.write("                           <li><a href=\"/jiksan/qalist\">Q&A 게시판</a></li>\r\n");
      out.write("                           ");
      out.write("\r\n");
      out.write("                           ");
      out.write("\r\n");
      out.write("                        </ol>\r\n");
      out.write("                     </li>\r\n");
      out.write("                  </ul>\r\n");
      out.write("               </div>\r\n");
      out.write("               ");
 } else if (loginUser != null && loginUser.getUserLv() > '1'){ 
      out.write("\r\n");
      out.write("               <nav >\r\n");
      out.write("                  <a href=\"/jiksan/logout\"><img\r\n");
      out.write("                     src=\"/jiksan/resources/main_images/nav-icon01.png\" alt=\"LOGOUT\"><span>LOGOUT</span></a>\r\n");
      out.write("                  <a href=\"/jiksan/views/user/userMyPage.jsp\">\r\n");
      out.write("                  ");
      out.write("\r\n");
      out.write("                     <img src=\"/jiksan/resources/main_images/nav-icon02.png\" alt=\"MY PAGE\"><span>MY PAGE</span></a>\r\n");
      out.write("                  <a href=\"javascript:redirectAdmin()\"><img\r\n");
      out.write("                     src=\"/jiksan/resources/main_images/nav-icon04.png\"\r\n");
      out.write("                     alt=\"RESERVATION\"><span>RESERVATION</span></a> <a href=\"#n\"\r\n");
      out.write("                     class=\"full-slide\">\r\n");
      out.write("                     <div class=\"row\">\r\n");
      out.write("                        <div class=\"three col\">\r\n");
      out.write("                           <div class=\"hamburger\" id=\"hamburger-1\">\r\n");
      out.write("                              <span class=\"line\"></span> <span class=\"line\"></span> <span\r\n");
      out.write("                                 class=\"line\"></span>\r\n");
      out.write("                           </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                     </div> <span style=\"font-weight: 500; color: #74afc9;\">전체메뉴</span>\r\n");
      out.write("                  </a>\r\n");
      out.write("               </nav>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"full-menu bg-white\">\r\n");
      out.write("               <div class=\"inner\">\r\n");
      out.write("                  <ul class=\"full-list inner cf\">\r\n");
      out.write("                     <li>\r\n");
      out.write("                        <div>병원안내</div>\r\n");
      out.write("                        <ol>\r\n");
      out.write("                           <li><a href=\"/jiksan/views/about/about-clinic.jsp\">병원안내</a></li>\r\n");
      out.write("                           <li><a href=\"/jiksan/views/about/about-services.jsp\">진료안내</a></li>\r\n");
      out.write("                           <li><a href=\"/jiksan/views/about/about-team.jsp\">의료진 소개</a></li>\r\n");
      out.write("                           <li><a href=\"/jiksan/views/about/contact-us.jsp\">오시는길</a></li>\r\n");
      out.write("                        </ol>\r\n");
      out.write("                     </li>\r\n");
      out.write("                     <li>\r\n");
      out.write("                        <div>당뇨클리닉</div>\r\n");
      out.write("                        <ol>\r\n");
      out.write("                           <li><a href=\"/jiksan/disease?disease_no=108\">당뇨병이란?</a></li>\r\n");
      out.write("                           <li><a href=\"/jiksan/views/diabetes/diabetes-diet.jsp\">당뇨병과 식생활</a></li>\r\n");
      out.write("                           <li><a href=\"/jiksan/views/diabetes/diabetes-exercise.jsp\">당뇨병과 운동</a></li>\r\n");
      out.write("                           <li><a href=\"/jiksan/disease?disease_no=108#complications\">당뇨병 합병증</a></li>\r\n");
      out.write("                        </ol>\r\n");
      out.write("                     </li>\r\n");
      out.write("                     <li>\r\n");
      out.write("                        <div>건강정보 관리</div>\r\n");
      out.write("                        <ol>\r\n");
      out.write("                           <li><a href=\"/jiksan/dlist\">질환백과</a></li>\r\n");
      out.write("                           ");
      out.write("\r\n");
      out.write("                        </ol>\r\n");
      out.write("                     </li>\r\n");
      out.write("                     <li>\r\n");
      out.write("                        <div>진료 예약 관리</div>\r\n");
      out.write("                        <ol>\r\n");
      out.write("                           <li><a href=\"/jiksan/views/reservation/about-appt.jsp\">예약안내</a></li>\r\n");
      out.write("                           <li><a href=\"/jiksan/reservation\">진료 예약하기</a></li>\r\n");
      out.write("                           ");
      out.write("\r\n");
      out.write("                        </ol>\r\n");
      out.write("                     </li>\r\n");
      out.write("                     <li>\r\n");
      out.write("                        <div>커뮤니티 관리</div>\r\n");
      out.write("                        <ol>\r\n");
      out.write("                           <li><a href=\"/jiksan/nlist\">공지사항</a></li>\r\n");
      out.write("                           <li><a href=\"/jiksan/faqlist\">자주묻는 질문</a></li>\r\n");
      out.write("                           <li><a href=\"/jiksan/qalist\">Q&A 게시판</a></li>\r\n");
      out.write("                           ");
      out.write("\r\n");
      out.write("                           ");
      out.write("\r\n");
      out.write("                        </ol>\r\n");
      out.write("                     </li>\r\n");
      out.write("                     <li>\r\n");
      out.write("                        <div>회원 관리</div>\r\n");
      out.write("                        <ol>\r\n");
      out.write("                           <li><a href=\"#\">회원 리스트</a></li>\r\n");
      out.write("                           <li><a href=\"#\">#</a></li>\r\n");
      out.write("                           <li><a href=\"#\">#</a></li>\r\n");
      out.write("                        </ol>\r\n");
      out.write("                     </li>\r\n");
      out.write("                  </ul>\r\n");
      out.write("               </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            ");
 } else { 
      out.write("\r\n");
      out.write("            <nav>\r\n");
      out.write("               <a href=\"/jiksan/logout\"><img\r\n");
      out.write("                  src=\"/jiksan/resources/main_images/nav-icon01.png\" alt=\"LOGOUT\"><span>LOGOUT</span></a>\r\n");
      out.write("                  <a href=\"/jiksan/views/user/userMyPage.jsp\">\r\n");
      out.write("                  ");
      out.write("\r\n");
      out.write("                     <img src=\"/jiksan/resources/main_images/nav-icon02.png\" alt=\"MY PAGE\"><span>MY PAGE</span></a>\r\n");
      out.write("                  <a href=\"javascript:redirect()\"><img\r\n");
      out.write("                  src=\"/jiksan/resources/main_images/nav-icon04.png\"\r\n");
      out.write("                  alt=\"RESERVATION\"><span>RESERVATION</span></a> <a href=\"#n\"\r\n");
      out.write("                  class=\"full-slide\">\r\n");
      out.write("                  <div class=\"row\">\r\n");
      out.write("                     <div class=\"three col\">\r\n");
      out.write("                        <div class=\"hamburger\" id=\"hamburger-1\">\r\n");
      out.write("                           <span class=\"line\"></span> <span class=\"line\"></span> <span\r\n");
      out.write("                              class=\"line\"></span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                     </div>\r\n");
      out.write("                  </div> <span style=\"font-weight: 500; color: #74afc9;\">전체메뉴</span>\r\n");
      out.write("               </a>\r\n");
      out.write("            </nav>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"full-menu bg-white\">\r\n");
      out.write("         <div class=\"inner\">\r\n");
      out.write("            <ul class=\"full-list inner cf\">\r\n");
      out.write("               <li>\r\n");
      out.write("                  <div>병원안내</div>\r\n");
      out.write("                  <ol>\r\n");
      out.write("                           <li><a href=\"/jiksan/views/about/about-clinic.jsp\">병원안내</a></li>\r\n");
      out.write("                           <li><a href=\"/jiksan/views/about/about-services.jsp\">진료안내</a></li>\r\n");
      out.write("                           <li><a href=\"/jiksan/views/about/about-team.jsp\">의료진 소개</a></li>\r\n");
      out.write("                           <li><a href=\"/jiksan/views/about/contact-us.jsp\">오시는길</a></li>\r\n");
      out.write("                  </ol>\r\n");
      out.write("               </li>\r\n");
      out.write("               <li>\r\n");
      out.write("                  <div>당뇨클리닉</div>\r\n");
      out.write("                  <ol>\r\n");
      out.write("                           <li><a href=\"/jiksan/disease?disease_no=108\">당뇨병이란?</a></li>\r\n");
      out.write("                           <li><a href=\"/jiksan/views/diabetes/diabetes-diet.jsp\">당뇨병과 식생활</a></li>\r\n");
      out.write("                           <li><a href=\"/jiksan/views/diabetes/diabetes-exercise.jsp\">당뇨병과 운동</a></li>\r\n");
      out.write("                           <li><a href=\"/jiksan/disease?disease_no=108#complications\">당뇨병 합병증</a></li>\r\n");
      out.write("                  </ol>\r\n");
      out.write("               </li>\r\n");
      out.write("               <li>\r\n");
      out.write("                  <div>건강정보</div>\r\n");
      out.write("                  <ol>\r\n");
      out.write("                     <li><a href=\"/jiksan/dlist\">질환백과</a></li>\r\n");
      out.write("                     ");
      out.write("\r\n");
      out.write("                  </ol>\r\n");
      out.write("               </li>\r\n");
      out.write("               <li>\r\n");
      out.write("                  <div>진료 예약</div>\r\n");
      out.write("                  <ol>\r\n");
      out.write("                     <li><a href=\"/jiksan/views/reservation/about-appt.jsp\">예약안내</a></li>\r\n");
      out.write("                     <li><a href=\"javascript:redirectAdmin()\">진료 예약하기</a></li>\r\n");
      out.write("                     ");
      out.write("\r\n");
      out.write("                  </ol>\r\n");
      out.write("               </li>\r\n");
      out.write("               <li>\r\n");
      out.write("                  <div>커뮤니티</div>\r\n");
      out.write("                  <ol>\r\n");
      out.write("                     <li><a href=\"/jiksan/nlist\">공지사항</a></li>\r\n");
      out.write("                     <li><a href=\"/jiksan/faqlist\">자주묻는 질문</a></li>\r\n");
      out.write("                     <li><a href=\"/jiksan/qalist\">Q&A 게시판</a></li>\r\n");
      out.write("                     ");
      out.write("\r\n");
      out.write("                     ");
      out.write("\r\n");
      out.write("                  </ol>\r\n");
      out.write("               </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("         </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      ");
 } 
      out.write("\r\n");
      out.write("      </section>\r\n");
      out.write("      </header>\r\n");
      out.write("   </div>\r\n");
      out.write("   </div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\t<div id=\"container\">\r\n");
      out.write("\t\t<section class=\"main-con01 mw\">\r\n");
      out.write("\t\t\t<div class=\"inner mw cf\">\r\n");
      out.write("\t\t\t\t<article class=\"con01-left\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"con01-visual\">\r\n");
      out.write("\t\t\t\t\t\t");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"main homepage slideshow\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<img class=\"slideshowPics\" src=\"/jiksan/resources/main_images/main_banner_01.jpg\"\t alt=\"코로나-19\"  style=\"width:660px\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<img class=\"slideshowPics\" src=\"/jiksan/resources/main_images/main_banner_02.jpg\" \t alt=\"가정의학과\" style=\"width:660px\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<img class=\"slideshowPics\" src=\"/jiksan/resources/main_images/main_banner_03.png\" \t alt=\"ICT교육원x직산가정의학과 의원\" style=\"width:660px\">\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t  <div class=\"w3-center w3-container w3-section w3-large w3-text-white w3-display-bottommiddle\" style=\"width:100%\">\r\n");
      out.write("\t\t\t\t\t\t\t    <div class=\"w3-left w3-hover-text-khaki\" onclick=\"plusDivs(-1)\">&#10094;</div>\r\n");
      out.write("\t\t\t\t\t\t\t    <div class=\"w3-right w3-hover-text-khaki\" onclick=\"plusDivs(1)\">&#10095;</div>\r\n");
      out.write("\t\t\t\t\t\t\t    <span class=\"w3-badge demo w3-border w3-transparent w3-hover-white\" onclick=\"currentDiv(1)\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t    <span class=\"w3-badge demo w3-border w3-transparent w3-hover-white\" onclick=\"currentDiv(2)\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t    <span class=\"w3-badge demo w3-border w3-transparent w3-hover-white\" onclick=\"currentDiv(3)\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t  </div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t\t\t\t\t\tvar slideIndex = 1;\r\n");
      out.write("\t\t\t\t\t\t\t\tshowDivs(slideIndex);\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t\t\t\t\t\tfunction plusDivs(n) {\r\n");
      out.write("\t\t\t\t\t\t\t\t  showDivs(slideIndex += n);\r\n");
      out.write("\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t\t\t\t\t\tfunction currentDiv(n) {\r\n");
      out.write("\t\t\t\t\t\t\t\t  showDivs(slideIndex = n);\r\n");
      out.write("\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t\t\t\t\t\tfunction showDivs(n) {\r\n");
      out.write("\t\t\t\t\t\t\t\t  var i;\r\n");
      out.write("\t\t\t\t\t\t\t\t  var x = document.getElementsByClassName(\"slideshowPics\");\r\n");
      out.write("\t\t\t\t\t\t\t\t  var dots = document.getElementsByClassName(\"demo\");\r\n");
      out.write("\t\t\t\t\t\t\t\t  if (n > x.length) {slideIndex = 1}\r\n");
      out.write("\t\t\t\t\t\t\t\t  if (n < 1) {slideIndex = x.length}\r\n");
      out.write("\t\t\t\t\t\t\t\t  for (i = 0; i < x.length; i++) {\r\n");
      out.write("\t\t\t\t\t\t\t\t    x[i].style.display = \"none\";  \r\n");
      out.write("\t\t\t\t\t\t\t\t  }\r\n");
      out.write("\t\t\t\t\t\t\t\t  for (i = 0; i < dots.length; i++) {\r\n");
      out.write("\t\t\t\t\t\t\t\t    dots[i].className = dots[i].className.replace(\" w3-white\", \"\");\r\n");
      out.write("\t\t\t\t\t\t\t\t  }\r\n");
      out.write("\t\t\t\t\t\t\t\t  x[slideIndex-1].style.display = \"block\";  \r\n");
      out.write("\t\t\t\t\t\t\t\t  dots[slideIndex-1].className += \" w3-white\";\r\n");
      out.write("\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\tcarousel();\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\tfunction carousel() {\r\n");
      out.write("\t\t\t\t\t\t\t\t  var i;\r\n");
      out.write("\t\t\t\t\t\t\t\t  var x = document.getElementsByClassName(\"slideshowPics\");\r\n");
      out.write("\t\t\t\t\t\t\t\t  for (i = 0; i < x.length; i++) {\r\n");
      out.write("\t\t\t\t\t\t\t\t    x[i].style.display = \"none\"; \r\n");
      out.write("\t\t\t\t\t\t\t\t  }\r\n");
      out.write("\t\t\t\t\t\t\t\t  slideIndex++;\r\n");
      out.write("\t\t\t\t\t\t\t\t  if (slideIndex > x.length) {slideIndex = 1} \r\n");
      out.write("\t\t\t\t\t\t\t\t  x[slideIndex-1].style.display = \"block\"; \r\n");
      out.write("\t\t\t\t\t\t\t\t  setTimeout(carousel, 3000); \r\n");
      out.write("\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t</script>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"con01-news cf\" >\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<h2><a href=\"/jiksan/dlist\" style=\"color:#fff; font-weight: 500;\">건강정보 검색</a></h2>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<div class=\"cf\">\r\n");
      out.write("\t\t\t\t\t\t\t <form name=\"search_disease\" method=\"post\" action=\"/jiksan/dsearch\">");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<select name=\"category\" class=\"form-control w25 vm search\">\r\n");
      out.write("\t\t\t\t\t\t      \t\t<option value= \"diseaseNm\">전체 검색</option>\r\n");
      out.write("\t\t\t\t\t\t      \t\t<option value=\"diseaseNm\" selected>질환 및 질병</option>\r\n");
      out.write("\t\t\t\t\t\t      \t\t<option value=\"diseaseNm\">검사 및 치료</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"search\" name=\"keyword\" size=40px; class=\"form-control w60 vm search\" placeholder=\"검색어 입력\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<button type=\"submit\" onClick=\"\" class=\"btn btn-default vm search\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<image src =\"/jiksan/resources/main_images/main-search-icon.png\" alt=\"검색하기\" width=\"30px\" style=\"align:center\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</button>");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("               <ul class=\"con01-box cf\">\r\n");
      out.write("                  <li>\r\n");
      out.write("                     <h3><a href=\"/jiksan/nlist\" target=\"_blank\">공지사항</a></h3>\r\n");
      out.write("                     <ol>\r\n");
      out.write("                        <li><a href=\"/jiksan/nlist\" target=\"_blank\" >「직산 가정의학과 의원」&nbsp;커뮤니티를&nbsp; 위한&nbsp; 최근&nbsp; 공지사항 </a></li>\r\n");
      out.write("                        <br>\r\n");
      out.write("                        <table id=\"newnotice\">\r\n");
      out.write("                        <tr><th>번호</th><th>제목</th><th>날짜</th></tr>\r\n");
      out.write("                        </table>\r\n");
      out.write("                     </ol>\r\n");
      out.write("                  </li>\r\n");
      out.write("               </ul>\r\n");
      out.write("\t\t\t\t<script type=\"text/javascript\">\r\n");
      out.write("               $(function(){\r\n");
      out.write("\t\t\t\t   $.ajax({\r\n");
      out.write("\t\t\t\t      url: \"/jiksan/ntop3\",\r\n");
      out.write("\t\t\t\t      type: \"get\",\r\n");
      out.write("\t\t\t\t      dataType: \"json\",\r\n");
      out.write("\t\t\t\t      success: function(data){\r\n");
      out.write("\t\t\t\t         console.log(\"success : \" + data);\r\n");
      out.write("\t\t\t\t         \r\n");
      out.write("\t\t\t\t         var jsonStr = JSON.stringify(data);\r\n");
      out.write("\t\t\t\t         \r\n");
      out.write("\t\t\t\t         var json = JSON.parse(jsonStr);\r\n");
      out.write("\t\t\t\t         \r\n");
      out.write("\t\t\t\t         var values = \"\";\r\n");
      out.write("\t\t\t\t         for(var i in json.list){\r\n");
      out.write("\t\t\t\t            values += \"<tr><td>\" + json.list[i].no\r\n");
      out.write("\t\t\t\t                        +\"</td><td><a href='/jiksan/ndetail.ad?notice_no=\"\r\n");
      out.write("\t\t\t\t                        +json.list[i].no +   \"'>\"\r\n");
      out.write("\t\t\t\t                        +decodeURIComponent(json.list[i].title)\r\n");
      out.write("\t\t\t\t                        +\"</a></td><td>\" + json.list[i].date + \"</td></tr>\";\r\n");
      out.write("\t\t\t\t         }\r\n");
      out.write("\t\t\t\t         \r\n");
      out.write("\t\t\t\t         $(\"#newnotice\").html($(\"#newnotice\").html() + values);\r\n");
      out.write("\t\t\t\t         \r\n");
      out.write("\t\t\t\t      },\r\n");
      out.write("\t\t\t\t      error: function(jqXHR, textstatus, errorthrown){\r\n");
      out.write("\t\t\t\t         console.log(\"error : \" + jqXHR + \", \" + textstatus + \", \" +errorthrown);\r\n");
      out.write("\t\t\t\t      }\r\n");
      out.write("\t\t\t\t   });\r\n");
      out.write("               });\r\n");
      out.write("               </script>\r\n");
      out.write("\t\t\t\t</article>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<article class=\"con01-right\">\r\n");
      out.write("\t\t\t\t\t<ul class=\"cf\">\r\n");
      out.write("\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"con01-hover\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<ol class=\"linehight-smoll\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"/jiksan/views/about/about-clinic.jsp\">병원안내</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"/jiksan/views/about/about-services.jsp\">진료안내</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"/jiksan/views/about/about-team.jsp\">의료진 소개</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"/jiksan/views/about/contact-us.jsp\">오시는길</a></li>                     \r\n");
      out.write("\t\t\t\t\t\t\t\t\t</ol>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"con01-inner\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<h3>병원안내</h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t<span>Welcome to our clinic!</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t<i class=\"xi-plus-thin\"></i>\t\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"con01-hover\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<ol>                                  \r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"/jiksan/disease?disease_no=108\">당뇨병이란?</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"/jiksan/views/diabetes/diabetes-diet.jsp\">당뇨병과 식생활</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"/jiksan/views/diabetes/diabetes-exercise.jsp\">당뇨병과 운동</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"/jiksan/disease?disease_no=108#complications\">당뇨병 합병증</a></li>\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</ol>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"con01-inner\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<h3>당뇨클리닉</h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t<span>Diabetes Clinic</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t<i class=\"xi-plus-thin\"></i>\t\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"con01-hover\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<ol>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"/jiksan/dlist\">질환백과</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</ol>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"con01-inner\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<h3>건강정보</h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t<span>Health Information</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t<i class=\"xi-plus-thin\"></i>\t\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"con01-hover\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<ol>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"/jiksan/views/reservation/about-appt.jsp\">예약안내</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"javascript:redirect()\">진료 예약하기</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</ol>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"con01-inner\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<h3>진료 예약</h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t<span>Medical Appointment</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t<i class=\"xi-plus-thin\"></i>\t\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"con01-hover\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<ol>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"/jiksan/nlist\">공지사항</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"/jiksan/faqlist\">자주묻는 질문</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"/jiksan/qalist\">Q&A 게시판</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</ol>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"con01-inner\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<h3>커뮤니티</h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t<span>Community</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t<i class=\"xi-plus-thin\"></i>\t\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"con01-hover\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<ol>\r\n");
      out.write("                                        <li><a href=\"/jiksan/views/user/userEnroll.jsp\">첫방문 고객 : 회원가입</a></li>\r\n");
      out.write("                                        <li><a href=\"/jiksan/views/user/userLogin.jsp\">기존 회원 : 로그인</a> </li>\r\n");
      out.write("                                    </ol>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"con01-inner\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<h3>로그인</h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t<span>◆ 더 많은 서비스 이용하기 ◆ </span>\r\n");
      out.write("\t\t\t\t\t\t\t\t<i class=\"xi-plus-thin\"></i>\t\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</article>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</section>\r\n");
      out.write("\t</div>\r\n");
      out.write(" </div>\r\n");
      out.write(" ");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("footer {\r\n");
      out.write("\tbackground:#3e4247;\r\n");
      out.write("\ttext-align : center;\r\n");
      out.write("\twidth : 100%;\r\n");
      out.write("\theight : 10%;\r\n");
      out.write("\tcolor: #d1d1d1;\r\n");
      out.write("\tfont-size : 0.8em;\r\n");
      out.write("\tpadding-top : 2%;\t\r\n");
      out.write("\tpadding-bottom : 2%;\t\r\n");
      out.write("\tline-height:1;\r\n");
      out.write("}\r\n");
      out.write("footer div h3 {\r\n");
      out.write("\tcolor: #fff;\r\n");
      out.write("\tfont-size : 1.2em;\r\n");
      out.write("\tfont-weight : none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".footer_btn_list li {\r\n");
      out.write(" float: auto; overflow: hidden;\r\n");
      out.write(" padding-right: 10px;\r\n");
      out.write(" display:inline;\r\n");
      out.write(" line-height:2;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#copyright, .footer_btn_list, address{\r\n");
      out.write("\tcolor: #9AA0A6 /* #80868B */\r\n");
      out.write("} \r\n");
      out.write("hr { clear : both; }\r\n");
      out.write("</style>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\t//개인정보처리방침\r\n");
      out.write("\tfunction OpenMemberPrivate() { // \"개인정보처리방침\" 만들기? 가져오기\r\n");
      out.write("\t\twindow.open(\r\n");
      out.write("\t\t\t\t\t\t\"/jiksan/resources/js/개인정보처리방침.asp\",\r\n");
      out.write("\t\t\t\t\t\t\"MemberPrivate\",\r\n");
      out.write("\t\t\t\t\t\t\"toolbar=0, left=100, top=50, location=0, directories=0, status=0, menubar=0, scrollbars=1, resizable=0, copyhistory=0, width=600 ,height=600\");\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<footer>\r\n");
      out.write("<div>\r\n");
      out.write("\t\t\t\t<h3><a href=\"/jiksan/index.jsp\" style=\"font-weight:500;\">직산 가정의학과 의원 Jiksan Family Medicine Clinic</a></h3><br>\r\n");
      out.write("\t\t\t\t<address>충남 천안시 서북구 직산읍 직산로 31 직산농협 2층 &nbsp;&nbsp;&nbsp;&nbsp; (041) 583-8500\r\n");
      out.write("\t\t\t\t</address>\r\n");
      out.write("\t\t\t\t<br> <br>\r\n");
      out.write("\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t평일 08:30 ~ 18:00 &nbsp;&nbsp;&nbsp;&nbsp; 토요일 09:00 ~ 13:00\r\n");
      out.write("\t\t\t\t\t&nbsp;&nbsp;&nbsp;&nbsp; 점심시간 13:00 ~ 14:00\r\n");
      out.write("\t\t\t\t\t&nbsp;&nbsp;&nbsp;&nbsp; 화요일 야간진료 21:00 까지 &nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t\t<i>일요일/공휴일은 휴무입니다.</i>\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t<label id=\"copyright\">Copyright ⓒ 2020 by Jiksan Family Medicine Clinic. All rights reserved.</label>\r\n");
      out.write("\t\t\t\t<br>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\t<ul class=\"footer_btn_list\">\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\" onclick=\"OpenMemberPrivate();\" style=\"cursor: pointer;\">개인정보처리방침</a></li>\r\n");
      out.write("\t\t\t\t\t<li> | </li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">이용약관</a></li>\r\n");
      out.write("\t\t\t\t\t<li> | </li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"/jiksan/views/about/contact-us.jsp\">찾아오시는길</a></li>\t\t\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("</footer>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
