/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.43
 * Generated at: 2020-12-31 02:46:51 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.about_005fdisease;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import user.model.vo.User;

public final class about_005fdisease_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/views/about_disease/../common/menubar.jsp", Long.valueOf(1609358179833L));
    _jspx_dependants.put("/views/about_disease/../common/header.jsp", Long.valueOf(1609376545487L));
    _jspx_dependants.put("/views/about_disease/../common/footer.jsp", Long.valueOf(1609361223069L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("user.model.vo.User");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>직산 가정의학과 의원</title>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"/jiksan/resources/css/jiksan-sidebar.css\"/>\r\n");
      out.write("<script type = \"text/javascript\" src = \"/jiksan/resources/js/jquery-3.5.1.min.js\"></script>\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=no, target-densitydpi=medium-dpi\">\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write('\r');
      out.write('\n');
	User loginMember = (User)session.getAttribute("loginUser"); 
      out.write("    \r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"/jiksan/resources/css/jiksan-header.css\"/>\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=no, target-densitydpi=medium-dpi\">\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"/jiksan/resources/css/main_slick.css\"/>\t\t");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/jiksan/resources/css/main_bootstrap.min.css\">\t\t");
      out.write("\r\n");
      out.write("<link href=\"/jiksan/resources/css/main_reset.css\" rel=\"stylesheet\" type=\"text/css\" />\t\t");
      out.write("\r\n");
      out.write("<link href=\"/jiksan/resources/css/main_common.css\" rel=\"stylesheet\" type=\"text/css\" />\t\t");
      out.write("\r\n");
      out.write("<link href=\"/jiksan/resources/css/main_main.css\" rel=\"stylesheet\" type=\"text/css\" />\t\t");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script type = \"text/javascript\" src = \"/jiksan/resources/js/jquery-3.5.1.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("$(document).ready(function(){\r\n");
      out.write("\t$(\".full-slide\").click(function() {\r\n");
      out.write("      $(\".full-menu\").stop().slideToggle(300);\r\n");
      out.write("\t\t\t$('.hamburger .line').css('transition', 'all 0.2s ease-in-out');\r\n");
      out.write("\r\n");
      out.write("\t\t\tif($('.hamburger').hasClass('is-active')){\r\n");
      out.write("\t\t\t\t$('.hamburger span:nth-child(1)').css({'transform':'translateY(0) rotate(0)'});\r\n");
      out.write("\t\t\t\t$('.hamburger span:nth-child(2)').css({'opacity':'1'});\r\n");
      out.write("\t\t\t\t$('.hamburger span:nth-child(3)').css({'transform':'translateY(0) rotate(0)'});\t\t\t\t\r\n");
      out.write("\t\t\t\t$('.hamburger').removeClass('is-active');\r\n");
      out.write("\t\t\t} else {\r\n");
      out.write("\t\t\t\t$('.hamburger span:nth-child(1)').css({'transform':'translateY(12px) rotate(45deg)'});\r\n");
      out.write("\t\t\t\t$('.hamburger span:nth-child(2)').css({'opacity':'0'});\r\n");
      out.write("\t\t\t\t$('.hamburger span:nth-child(3)').css({'transform':'translateY(-4px) rotate(-45deg)'});\r\n");
      out.write("\t\t\t\t$('.hamburger').addClass('is-active');\r\n");
      out.write("\t\t\t}\r\n");
      out.write("    });\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\tfunction setCookie(name, value, expiredays) {\r\n");
      out.write("\t\tvar todayDate = new Date();\r\n");
      out.write("\t\ttodayDate.setDate(todayDate.getDate() + expiredays);\r\n");
      out.write("\t\tdocument.cookie = name + \"=\" + escape(value) + \"; path=/; expires=\" + todayDate.toGMTString() + \";\"\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction getCookie(name) {\r\n");
      out.write("\t\tvar nameOfCookie = name + \"=\";\r\n");
      out.write("\t\tvar x = 0;\r\n");
      out.write("\t\twhile (x <= document.cookie.length) {\r\n");
      out.write("\t\t\tvar y = (x + nameOfCookie.length);\r\n");
      out.write("\t\t\tif (document.cookie.substring(x, y) == nameOfCookie) {\r\n");
      out.write("\t\t\t\tif ((endOfCookie = document.cookie.indexOf(\";\", y)) == -1)\r\n");
      out.write("\t\t\t\t\tendOfCookie = document.cookie.length;\r\n");
      out.write("\t\t\t\treturn unescape(document.cookie.substring(y, endOfCookie));\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tx = document.cookie.indexOf(\" \", x) + 1;\r\n");
      out.write("\t\t\tif (x == 0)\r\n");
      out.write("\t\t\t\tbreak;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\treturn \"\";\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div id=\"wrap\" class=\"mw1600\" style=\"position:relative;\">\r\n");
      out.write("\t\t<div class=\"mw1600\">\r\n");
      out.write("\t<header class=\"bg-white mw\">\r\n");
      out.write("\t\t<div id=\"header-wrap\" class=\"inner cf\">\r\n");
      out.write("\t\t\t<a href=\"/jiksan/index.jsp\"><img src=\"/jiksan/resources/main_images/jiksan_logo.png\" alt=\"직산 가정의학과 의원\" style=\"width: auto; max-width: 22%\"></a>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t<nav>\r\n");
      out.write("\t\t\t\t<a href=\"/jiksan/views/user/userLogin.jsp\"><img src=\"/jiksan/resources/main_images/nav-icon01.png\" alt=\"LOGIN\"><span>LOGIN</span></a>\r\n");
      out.write("\t\t\t\t<a href=\"/jiksan/views/user/userEnroll.jsp\"><img src=\"/jiksan/resources/main_images/nav-icon02.png\" alt=\"JOIN\"><span>JOIN</span></a>\r\n");
      out.write("\t\t\t\t<a href=\"/jiksan/contact-us\"><img src=\"/jiksan/resources/main_images/nav-icon03.png\" alt=\"CONTACT US\"><span>CONTACT US</span></a>\r\n");
      out.write("\t\t\t\t<a href=\"#n\" class=\"full-slide\">\r\n");
      out.write("\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"three col\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"hamburger\" id=\"hamburger-1\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"line\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"line\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"line\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<span style=\"font-weight: 500; color: #74afc9;\">전체메뉴</span>\r\n");
      out.write("\t\t\t\t</a>\r\n");
      out.write("\t\t\t</nav>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"full-menu bg-white\">\r\n");
      out.write("\t\t\t<div class=\"inner\">\r\n");
      out.write("\t\t\t\t<ul class=\"full-list inner cf\">\r\n");
      out.write("\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t<div>병원안내</div>\r\n");
      out.write("\t\t\t\t\t\t<ol>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"/jiksan/about-clinic\">병원안내</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"/jiksan/about-services\">진료안내</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"/jiksan/about-team\">의료진 소개</a></li>\r\n");
      out.write("                            <li><a href=\"/jiksan/contact-us\">오시는길</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ol>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t<div>당뇨클리닉</div>\r\n");
      out.write("\t\t\t\t\t\t<ol>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"/jiksan/diabetes\" >당뇨병이란?</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"/jiksan/diabetes-test\" >당뇨병 검사</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"/jiksan/diabetes-diet\" >당뇨병과 식생활</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"/jiksan/diabetes-exercise\" >당뇨병과 운동</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"/jiksan/diabetes-complications\" >당뇨병 합병증</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ol>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t<div>건강정보</div>\r\n");
      out.write("\t\t\t\t\t\t<ol>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"/jiksan/about-disease\">질환백과</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</ol>\t\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t<div>진료 예약</div>\r\n");
      out.write("\t\t\t\t\t\t<ol>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\">예약안내</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\">진료 예약하기</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</ol>\t\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t<div>커뮤니티</div>\r\n");
      out.write("\t\t\t\t\t\t<ol>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"/jiksan/views/notice/nlist\">공지사항</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"/jiksan/views/faq/faqlist\">자주묻는 질문</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\">Q&A 게시판</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</ol>\t\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</header>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("/* html { font-size: calc(1em + 1vw) } */\r\n");
      out.write("body, div, dl, dt, dd, h1, h2, h3, h4, h5, h6, pre, legend, \r\n");
      out.write("p, form, fieldset, input, textarea, select, blockquote, th, td { font-family: 'Nanum Gothic', sans-serif !important; line-height: 1.5; }\r\n");
      out.write("\r\n");
      out.write(".nav { display: flex; align: center; width: 100%; height:50px; }\r\n");
      out.write(".nav .gnb {  margin : auto; }\r\n");
      out.write(".nav .gnb li {display: inline-block; font-size: 17px; font-weight: 600; }\r\n");
      out.write(".nav .gnb li a { display: block; color: #272727; text-align: center; padding: 0 50px; line-height: 50px; height: 50px; text-decoration: none; }\r\n");
      out.write("\r\n");
      out.write("/* .nav .gnb .dropbtn {width: 40px;} */\r\n");
      out.write(".nav .gnb .dropbtn:hover {color: #fff; background: #0071bc}\r\n");
      out.write("\r\n");
      out.write(".nav .gnb .dropdown-content { display: none; align: center; position: absolute; width: 100%; max-width: 180px; z-index: 9000; }\r\n");
      out.write(".nav .gnb .dropdown-content a { color: #265277; padding: 0px 20px; text-decoration: none; display: block; align: center; text-align: center; font-size: 14px; background: rgba(255,255,255, 0.94);}\r\n");
      out.write(".nav .gnb .dropdown-content a:first-child { border-top: none; }\r\n");
      out.write(".nav .gnb .dropdown:hover .dropdown-content { display: block; align: center;}\r\n");
      out.write(".nav .gnb .dropdown-content a:hover {color: #fff; background: #0071bc}}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"nav\">\r\n");
      out.write("\t\t\t\t<ul class=\"gnb\">\r\n");
      out.write("\t\t\t\t\t<li class=\"dropdown\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"/jiksan/about-clinic\" class=\"dropbtn\">병원안내</a>\r\n");
      out.write("\t\t\t\t\t\t<div  class=\"dropdown-content\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"/jiksan/about-services\">진료안내</a>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"/jiksan/about-team\">의료진 소개</a>\r\n");
      out.write("                            <a href=\"/jiksan/contact-us\">오시는길</a>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<li class=\"dropdown\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"/jiksan/diabetes\" class=\"dropbtn\">당뇨클리닉</a>\r\n");
      out.write("\t\t\t\t\t\t<div  class=\"dropdown-content\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"/jiksan/diabetes\" >당뇨병이란?</a>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"/jiksan/diabetes-test\" >당뇨병 검사</a>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"/jiksan/diabetes-diet\" >당뇨병과 식생활</a>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"/jiksan/diabetes-exercise\" >당뇨병과 운동</a>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"/jiksan/diabetes-complications\" >당뇨병 합병증</a>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<li class=\"dropdown\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"/jiksan/about-disease\"  class=\"dropbtn\">건강정보</a>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"dropdown-content\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"/jiksan/about-disease\">질환백과</a>\r\n");
      out.write("\t\t\t\t\t\t\t");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<li class=\"dropdown\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#\"  class=\"dropbtn\">진료 예약</a>\r\n");
      out.write("\t\t\t\t\t\t<div  class=\"dropdown-content\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\">예약안내</a>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\">진료 예약하기</a>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<li class=\"dropdown\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"/jiksan/views/notice/noticeListView.jsp\"  class=\"dropbtn\">커뮤니티</a>\r\n");
      out.write("\t\t\t\t\t\t<div  class=\"dropdown-content\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"/jiksan/views/notice/nlist\">공지사항</a>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"/jiksan/views/faq/faqlist\">자주묻는 질문</a>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\">Q&A 게시판</a>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("<div class=\"lnb\">    \r\n");
      out.write("\t<h2 class=\"lnb_title\">병원안내</h2>\t\t\r\n");
      out.write("\t<ul class=\"lnb_menu\">\r\n");
      out.write("\t\t<li class=\"on\"><a href=\"#\">병원안내</a></li>\r\n");
      out.write("\t\t<li><a href=\"#\">진료안내</a></li>\r\n");
      out.write("\t\t<li><a href=\"#\">의료진소개</a></li>\r\n");
      out.write("\t\t<li><a href=\"#\">오시는길</a>\r\n");
      out.write("\t</ul>            \r\n");
      out.write("\t<div class=\"lnb_box01\">\r\n");
      out.write("\t\t<dl class=\"lnb_txt01\">\r\n");
      out.write("\t\t\t<dt><b>직산 가정의학과 의원</b></dt>\r\n");
      out.write("\t\t</dl>\r\n");
      out.write("\t\t<p class=\"num\">041-573-5595</p>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"lnb_box02\">\r\n");
      out.write("\t\t<p class=\"num02\"><span>평일</span> 08:30 ~ 18:00</p>\r\n");
      out.write("\t\t<p class=\"num02\"><span>토요일</span> 09:00 ~ 13:00</p>\r\n");
      out.write("\t\t<p class=\"num02\"><span>점심시간</span> 13:00 ~ 14:00</p>\r\n");
      out.write("\t\t<p class=\"time_comment\">화요일 야간진료는 21:00 까지이며, <br>일요일/공휴일은 휴무입니다.</p>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<hr id=\"floatClear\">\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div style=\"margin: 220px; padding: 10px;\">\r\n");
      out.write(" \r\n");
      out.write(" <div class=\"searchTypeSec\" id=\"diseaTab\">\r\n");
      out.write("\t\r\n");
      out.write("\t<a href=\"#\" class=\"menu1 on\"><span>질환명 검색</span></a>\r\n");
      out.write("\t<div class=\"tabSearchList cont3\" style=\"height: 259px; display: block;\">\r\n");
      out.write("\t\t<div class=\"regionSearch\">\r\n");
      out.write("\t\t\t<dl class=\"regSearchdl\">\r\n");
      out.write("\t\t\t\t<dt><label for=\"regionSrc\">질환명 검색</label></dt>\r\n");
      out.write("\t\t\t\t<dd>\r\n");
      out.write("\t\t\t\t\t<ul class=\"SearchBox\">\r\n");
      out.write("\t\t\t\t\t\t<li class=\"searchIcon\"><span autocomplete=\"off\"></span></li>\r\n");
      out.write("\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t<form id=\"searchFrm\" method=\"get\" action=\"/asan/healthinfo/disease/diseaseList.do\" autocomplete=\"off\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" title=\"질환명 검색\" id=\"regionSrc\" name=\"searchKeyword\" value=\"\" placeholder=\"질환명 검색\" style=\"width:359px;\">\r\n");
      out.write("\t\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</dd>\r\n");
      out.write("\t\t\t\t<dd class=\"searchBtn\"><a href=\"/asan/healthinfo/disease/diseaseList.do\" onclick=\"$('#searchFrm').submit(); return false; ga('send', 'event', '건강정보-질환백과', 'CLICK', '질환명 검색');\">검색</a></dd>\r\n");
      out.write("\t\t\t</dl>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<a href=\"#\" class=\"menu3\"><span>질환별</span></a>\r\n");
      out.write("\t<div class=\"tabSearchList cont2\" style=\"height: 259px; display: none;\">\r\n");
      out.write("\t\t<ul class=\"tabSearchListUl clearfix\">\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t<li class=\"listCon\">\r\n");
      out.write("\t\t\t\t\t<a class=\"\" href=\"/asan/healthinfo/disease/diseaseList.do?diseaseKindId=C000001\">감염성질환</a>\r\n");
      out.write("\t\t\t\t</li>\t\t\t\r\n");
      out.write("\t\t\t\t<li class=\"listCon\">\r\n");
      out.write("\t\t\t\t\t<a class=\"\" href=\"/asan/healthinfo/disease/diseaseList.do?diseaseKindId=C000002\">건강증진</a>\r\n");
      out.write("\t\t\t\t</li>\t\t\t\r\n");
      out.write("\t\t\t\t<li class=\"listCon\">\r\n");
      out.write("\t\t\t\t\t<a class=\"\" href=\"/asan/healthinfo/disease/diseaseList.do?diseaseKindId=C000003\">귀코목질환</a>\r\n");
      out.write("\t\t\t\t</li>\t\t\t\r\n");
      out.write("\t\t\t\t<li class=\"listCon\">\r\n");
      out.write("\t\t\t\t\t<a class=\"\" href=\"/asan/healthinfo/disease/diseaseList.do?diseaseKindId=C000004\">근골격질환</a>\r\n");
      out.write("\t\t\t\t</li>\t\t\t\r\n");
      out.write("\t\t\t\t<li class=\"listCon last\">\r\n");
      out.write("\t\t\t\t\t<a class=\"\" href=\"/asan/healthinfo/disease/diseaseList.do?diseaseKindId=C000005\">눈질환</a>\r\n");
      out.write("\t\t\t\t</li>\t\t\t\r\n");
      out.write("\t\t\t\t<li class=\"listCon\">\r\n");
      out.write("\t\t\t\t\t<a class=\"\" href=\"/asan/healthinfo/disease/diseaseList.do?diseaseKindId=C000006\">뇌신경정신질환</a>\r\n");
      out.write("\t\t\t\t</li>\t\t\t\r\n");
      out.write("\t\t\t\t<li class=\"listCon\">\r\n");
      out.write("\t\t\t\t\t<a class=\"\" href=\"/asan/healthinfo/disease/diseaseList.do?diseaseKindId=C000007\">성형미용 및 재건</a>\r\n");
      out.write("\t\t\t\t</li>\t\t\t\r\n");
      out.write("\t\t\t\t<li class=\"listCon\">\r\n");
      out.write("\t\t\t\t\t<a class=\"\" href=\"/asan/healthinfo/disease/diseaseList.do?diseaseKindId=C000008\">소아청소년질환</a>\r\n");
      out.write("\t\t\t\t</li>\t\t\t\r\n");
      out.write("\t\t\t\t<li class=\"listCon\">\r\n");
      out.write("\t\t\t\t\t<a class=\"\" href=\"/asan/healthinfo/disease/diseaseList.do?diseaseKindId=C000009\">소화기질환</a>\r\n");
      out.write("\t\t\t\t</li>\t\t\t\r\n");
      out.write("\t\t\t\t<li class=\"listCon last\">\r\n");
      out.write("\t\t\t\t\t<a class=\"\" href=\"/asan/healthinfo/disease/diseaseList.do?diseaseKindId=C000010\">순환기질환</a>\r\n");
      out.write("\t\t\t\t</li>\t\t\t\r\n");
      out.write("\t\t\t\t<li class=\"listCon\">\r\n");
      out.write("\t\t\t\t\t<a class=\"\" href=\"/asan/healthinfo/disease/diseaseList.do?diseaseKindId=C000011\">신장비뇨기질환</a>\r\n");
      out.write("\t\t\t\t</li>\t\t\t\r\n");
      out.write("\t\t\t\t<li class=\"listCon\">\r\n");
      out.write("\t\t\t\t\t<a class=\"\" href=\"/asan/healthinfo/disease/diseaseList.do?diseaseKindId=C000012\">여성질환</a>\r\n");
      out.write("\t\t\t\t</li>\t\t\t\r\n");
      out.write("\t\t\t\t<li class=\"listCon\">\r\n");
      out.write("\t\t\t\t\t<a class=\"\" href=\"/asan/healthinfo/disease/diseaseList.do?diseaseKindId=C000013\">유방내분비질환</a>\r\n");
      out.write("\t\t\t\t</li>\t\t\t\r\n");
      out.write("\t\t\t\t<li class=\"listCon\">\r\n");
      out.write("\t\t\t\t\t<a class=\"\" href=\"/asan/healthinfo/disease/diseaseList.do?diseaseKindId=C000014\">유전질환</a>\r\n");
      out.write("\t\t\t\t</li>\t\t\t\r\n");
      out.write("\t\t\t\t<li class=\"listCon last\">\r\n");
      out.write("\t\t\t\t\t<a class=\"\" href=\"/asan/healthinfo/disease/diseaseList.do?diseaseKindId=C000015\">응급질환</a>\r\n");
      out.write("\t\t\t\t</li>\t\t\t\r\n");
      out.write("\t\t\t\t<li class=\"listCon\">\r\n");
      out.write("\t\t\t\t\t<a class=\"\" href=\"/asan/healthinfo/disease/diseaseList.do?diseaseKindId=C000016\">종양혈액질환</a>\r\n");
      out.write("\t\t\t\t</li>\t\t\t\r\n");
      out.write("\t\t\t\t<li class=\"listCon\">\r\n");
      out.write("\t\t\t\t\t<a class=\"\" href=\"/asan/healthinfo/disease/diseaseList.do?diseaseKindId=C000017\">치과질환</a>\r\n");
      out.write("\t\t\t\t</li>\t\t\t\r\n");
      out.write("\t\t\t\t<li class=\"listCon\">\r\n");
      out.write("\t\t\t\t\t<a class=\"\" href=\"/asan/healthinfo/disease/diseaseList.do?diseaseKindId=C000018\">피부질환</a>\r\n");
      out.write("\t\t\t\t</li>\t\t\t\r\n");
      out.write("\t\t\t\t<li class=\"listCon\">\r\n");
      out.write("\t\t\t\t\t<a class=\"\" href=\"/asan/healthinfo/disease/diseaseList.do?diseaseKindId=C000019\">호흡기질환</a>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t<li class=\"listCon last\">\r\n");
      out.write("\t\t\t\t\t<a class=\"\" href=\"/asan/healthinfo/disease/diseaseList.do?diseaseKindId=C000020\">기타</a>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t \r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write(" \r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("footer {\r\n");
      out.write("\tbackground:#3e4247;\r\n");
      out.write("\ttext-align : center;\r\n");
      out.write("\twidth : 100%;\r\n");
      out.write("\theight : 10%;\r\n");
      out.write("\tcolor: #d1d1d1;\r\n");
      out.write("\tfont-size : 0.8em;\r\n");
      out.write("\tpadding-top : 2%;\t\r\n");
      out.write("\tpadding-bottom : 2%;\t\r\n");
      out.write("\tline-height:1;\r\n");
      out.write("}\r\n");
      out.write("footer div h3 {\r\n");
      out.write("\tcolor: #fff;\r\n");
      out.write("\tfont-size : 1.2em;\r\n");
      out.write("\tfont-weight : none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".footer_btn_list li {\r\n");
      out.write(" float: auto; overflow: hidden;\r\n");
      out.write(" padding-right: 10px;\r\n");
      out.write(" display:inline;\r\n");
      out.write(" line-height:2;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#copyright, .footer_btn_list, address{\r\n");
      out.write("\tcolor: #9AA0A6 /* #80868B */\r\n");
      out.write("} \r\n");
      out.write("hr { clear : both; }\r\n");
      out.write("</style>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\t//개인정보처리방침\r\n");
      out.write("\tfunction OpenMemberPrivate() { // \"개인정보처리방침\" 만들기? 가져오기\r\n");
      out.write("\t\twindow.open(\r\n");
      out.write("\t\t\t\t\t\t\"/jiksan/resources/js/개인정보처리방침.asp\",\r\n");
      out.write("\t\t\t\t\t\t\"MemberPrivate\",\r\n");
      out.write("\t\t\t\t\t\t\"toolbar=0, left=100, top=50, location=0, directories=0, status=0, menubar=0, scrollbars=1, resizable=0, copyhistory=0, width=600 ,height=600\");\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<footer>\r\n");
      out.write("<div>\r\n");
      out.write("\t\t\t\t<h3>직산 가정의학과 의원 Jiksan Family Medicine Clinic</h3><br>\r\n");
      out.write("\t\t\t\t<address>충남 천안시 서북구 직산읍 직산로 31 직산농협 2층 &nbsp;&nbsp;&nbsp;&nbsp; (041) 583-8500\r\n");
      out.write("\t\t\t\t</address>\r\n");
      out.write("\t\t\t\t<br> <br>\r\n");
      out.write("\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t평일 08:30 ~ 18:00 &nbsp;&nbsp;&nbsp;&nbsp; 토요일 09:00 ~ 13:00\r\n");
      out.write("\t\t\t\t\t&nbsp;&nbsp;&nbsp;&nbsp; 점심시간 13:00 ~ 14:00\r\n");
      out.write("\t\t\t\t\t&nbsp;&nbsp;&nbsp;&nbsp; 화요일 야간진료 21:00 까지 &nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t\t<i>일요일/공휴일은 휴무입니다.</i>\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t<label id=\"copyright\">Copyright ⓒ 2020 by Jiksan Family Medicine Clinic. All rights reserved.</label>\r\n");
      out.write("\t\t\t\t<br>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\t<ul class=\"footer_btn_list\">\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\" onclick=\"OpenMemberPrivate();\" style=\"cursor: pointer;\">개인정보처리방침</a></li>\r\n");
      out.write("\t\t\t\t\t<li> | </li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">이용약관</a></li>\r\n");
      out.write("\t\t\t\t\t<li> | </li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"/jiksan/contact-us\">찾아오시는길</a></li>\t\t\t");
      out.write("\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("</footer>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
