/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.43
 * Generated at: 2021-01-05 19:22:41 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.faq;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.ArrayList;
import faq.model.vo.Faq;

public final class faqAdminListView_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/views/faq/../common/footer.jsp", Long.valueOf(1609825492674L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("faq.model.vo.Faq");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");

	ArrayList<Faq> list = (ArrayList<Faq>)request.getAttribute("list");

      out.write("    \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>jiksan</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<h1>FAQ 자주묻는 질문(관리자)</h1>\r\n");
      out.write("\r\n");
      out.write("<hr>\r\n");
      out.write("<br>\r\n");
      out.write("<table align=\"center\" width=\"500\" border=\"1\" cellspacing=\"0\" cellpadding=\"1\">\r\n");
      out.write("<tr><th><input type=\"checkbox\"></th><th>순번</th><th>제목</th><th>작성일시</th></tr>\r\n");
 for(Faq f : list){ 
      out.write("\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td align=\"center\"><input type=\"checkbox\"></td>\r\n");
      out.write("\t\t<td align=\"center\">");
      out.print( f.getFaqNo() );
      out.write("</td>\r\n");
      out.write("\t\t<td align=\"center\"><a href=\"/jiksan/faqdetail?faq_no=");
      out.print( f.getFaqNo() );
      out.write('"');
      out.write('>');
      out.print( f.getFaqTitle() );
      out.write("</a></td>\r\n");
      out.write("\t\t<td align=\"center\">");
      out.print( f.getFaqDate() );
      out.write("</td>\r\n");
      out.write("\t</tr>\r\n");
 } //for each 
      out.write("\r\n");
      out.write("</table>\r\n");
      out.write("<br> <br>\r\n");
      out.write("<center>\r\n");
      out.write("<button onclick=\"javascript:location.href='/jiksan/views/faq/faqWriteForm.jsp';\">FAQ 등록</button>\r\n");
      out.write("</center>\r\n");
      out.write("<hr>\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("footer {\r\n");
      out.write("\tbackground:#3e4247;\r\n");
      out.write("\ttext-align : center;\r\n");
      out.write("\twidth : 100%;\r\n");
      out.write("\theight : 10%;\r\n");
      out.write("\tcolor: #d1d1d1;\r\n");
      out.write("\tfont-size : 0.8em;\r\n");
      out.write("\tpadding-top : 2%;\t\r\n");
      out.write("\tpadding-bottom : 2%;\t\r\n");
      out.write("\tline-height:1;\r\n");
      out.write("}\r\n");
      out.write("footer div h3 {\r\n");
      out.write("\tcolor: #fff;\r\n");
      out.write("\tfont-size : 1.2em;\r\n");
      out.write("\tfont-weight : none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".footer_btn_list li {\r\n");
      out.write(" float: auto; overflow: hidden;\r\n");
      out.write(" padding-right: 10px;\r\n");
      out.write(" display:inline;\r\n");
      out.write(" line-height:2;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#copyright, .footer_btn_list, address{\r\n");
      out.write("\tcolor: #9AA0A6 /* #80868B */\r\n");
      out.write("} \r\n");
      out.write("hr { clear : both; }\r\n");
      out.write("</style>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\t//개인정보처리방침\r\n");
      out.write("\tfunction OpenMemberPrivate() { // \"개인정보처리방침\" 만들기? 가져오기\r\n");
      out.write("\t\twindow.open(\r\n");
      out.write("\t\t\t\t\t\t\"/jiksan/resources/js/개인정보처리방침.asp\",\r\n");
      out.write("\t\t\t\t\t\t\"MemberPrivate\",\r\n");
      out.write("\t\t\t\t\t\t\"toolbar=0, left=100, top=50, location=0, directories=0, status=0, menubar=0, scrollbars=1, resizable=0, copyhistory=0, width=600 ,height=600\");\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<footer>\r\n");
      out.write("<div>\r\n");
      out.write("\t\t\t\t<h3>직산 가정의학과 의원 Jiksan Family Medicine Clinic</h3><br>\r\n");
      out.write("\t\t\t\t<address>충남 천안시 서북구 직산읍 직산로 31 직산농협 2층 &nbsp;&nbsp;&nbsp;&nbsp; (041) 583-8500\r\n");
      out.write("\t\t\t\t</address>\r\n");
      out.write("\t\t\t\t<br> <br>\r\n");
      out.write("\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t평일 08:30 ~ 18:00 &nbsp;&nbsp;&nbsp;&nbsp; 토요일 09:00 ~ 13:00\r\n");
      out.write("\t\t\t\t\t&nbsp;&nbsp;&nbsp;&nbsp; 점심시간 13:00 ~ 14:00\r\n");
      out.write("\t\t\t\t\t&nbsp;&nbsp;&nbsp;&nbsp; 화요일 야간진료 21:00 까지 &nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t\t<i>일요일/공휴일은 휴무입니다.</i>\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t<label id=\"copyright\">Copyright ⓒ 2020 by Jiksan Family Medicine Clinic. All rights reserved.</label>\r\n");
      out.write("\t\t\t\t<br>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\t<ul class=\"footer_btn_list\">\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\" onclick=\"OpenMemberPrivate();\" style=\"cursor: pointer;\">개인정보처리방침</a></li>\r\n");
      out.write("\t\t\t\t\t<li> | </li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">이용약관</a></li>\r\n");
      out.write("\t\t\t\t\t<li> | </li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"/jiksan/contact-us\">찾아오시는길</a></li>\t\t\t");
      out.write("\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("</footer>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
