/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.43
 * Generated at: 2021-01-04 18:24:35 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.faq;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import faq.model.vo.Faq;
import user.model.vo.User;

public final class faqWriteForm_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/views/faq/../common/footer.jsp", Long.valueOf(1609361223069L));
    _jspx_dependants.put("/views/faq/../common/header.jsp", Long.valueOf(1609784230047L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("faq.model.vo.Faq");
    _jspx_imports_classes.add("user.model.vo.User");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

	Faq faq = (Faq)request.getAttribute("faq");

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>jiksan</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write('\r');
      out.write('\n');
	User loginUser = (User)session.getAttribute("loginUser"); 
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" \thref=\"/jiksan/resources/css/jiksan-header.css\" />\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"/jiksan/resources/js/jquery-3.5.1.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("$(document).ready(function(){\r\n");
      out.write("\t$(\".full-slide\").click(function() {\r\n");
      out.write("      $(\".full-menu\").stop().slideToggle(300);\r\n");
      out.write("\t\t\t$('.hamburger .line').css('transition', 'all 0.2s ease-in-out');\r\n");
      out.write("\r\n");
      out.write("\t\t\tif($('.hamburger').hasClass('is-active')){\r\n");
      out.write("\t\t\t\t$('.hamburger span:nth-child(1)').css({'transform':'translateY(0) rotate(0)'});\r\n");
      out.write("\t\t\t\t$('.hamburger span:nth-child(2)').css({'opacity':'1'});\r\n");
      out.write("\t\t\t\t$('.hamburger span:nth-child(3)').css({'transform':'translateY(0) rotate(0)'});\t\t\t\t\r\n");
      out.write("\t\t\t\t$('.hamburger').removeClass('is-active');\r\n");
      out.write("\t\t\t} else {\r\n");
      out.write("\t\t\t\t$('.hamburger span:nth-child(1)').css({'transform':'translateY(12px) rotate(45deg)'});\r\n");
      out.write("\t\t\t\t$('.hamburger span:nth-child(2)').css({'opacity':'0'});\r\n");
      out.write("\t\t\t\t$('.hamburger span:nth-child(3)').css({'transform':'translateY(-4px) rotate(-45deg)'});\r\n");
      out.write("\t\t\t\t$('.hamburger').addClass('is-active');\r\n");
      out.write("\t\t\t}\r\n");
      out.write("    });\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\tfunction setCookie(name, value, expiredays) {\r\n");
      out.write("\t\tvar todayDate = new Date();\r\n");
      out.write("\t\ttodayDate.setDate(todayDate.getDate() + expiredays);\r\n");
      out.write("\t\tdocument.cookie = name + \"=\" + escape(value) + \"; path=/; expires=\" + todayDate.toGMTString() + \";\"\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction getCookie(name) {\r\n");
      out.write("\t\tvar nameOfCookie = name + \"=\";\r\n");
      out.write("\t\tvar x = 0;\r\n");
      out.write("\t\twhile (x <= document.cookie.length) {\r\n");
      out.write("\t\t\tvar y = (x + nameOfCookie.length);\r\n");
      out.write("\t\t\tif (document.cookie.substring(x, y) == nameOfCookie) {\r\n");
      out.write("\t\t\t\tif ((endOfCookie = document.cookie.indexOf(\";\", y)) == -1)\r\n");
      out.write("\t\t\t\t\tendOfCookie = document.cookie.length;\r\n");
      out.write("\t\t\t\treturn unescape(document.cookie.substring(y, endOfCookie));\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tx = document.cookie.indexOf(\" \", x) + 1;\r\n");
      out.write("\t\t\tif (x == 0)\r\n");
      out.write("\t\t\t\tbreak;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\treturn \"\";\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\t<div id=\"wrap\" class=\"mw1600\" style=\"position: relative;\">\r\n");
      out.write("\t\t<div class=\"mw1600\">\r\n");
      out.write("\t\t\t<header class=\"bg-white mw\">\r\n");
      out.write("\t\t\t\t<div id=\"header-wrap\" class=\"inner cf\">\r\n");
      out.write("\t\t\t\t\t<a href=\"/jiksan/index.jsp\"><img\r\n");
      out.write("\t\t\t\t\t\tsrc=\"/jiksan/resources/main_images/jiksan_logo.png\"\r\n");
      out.write("\t\t\t\t\t\talt=\"직산 가정의학과 의원\" style=\"width: auto; max-width: 22%\"></a>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<section>\r\n");
      out.write("\t\t\t\t\t\t");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t");
 if(loginUser == null){ //로그인 안 했다면 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<nav>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"/jiksan/views/user/userLogin.jsp\"><img\r\n");
      out.write("\t\t\t\t\t\t\t\tsrc=\"/jiksan/resources/main_images/nav-icon01.png\" alt=\"LOGIN\"><span>LOGIN</span></a>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"/jiksan/views/user/userEnroll.jsp\"><img\r\n");
      out.write("\t\t\t\t\t\t\t\tsrc=\"/jiksan/resources/main_images/nav-icon02.png\" alt=\"JOIN\"><span>JOIN</span></a>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"/jiksan/contact-us\"><img\r\n");
      out.write("\t\t\t\t\t\t\t\tsrc=\"/jiksan/resources/main_images/nav-icon03.png\"\r\n");
      out.write("\t\t\t\t\t\t\t\talt=\"CONTACT US\"><span>CONTACT US</span></a> <a href=\"#n\"\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"full-slide\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"three col\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"hamburger\" id=\"hamburger-1\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<span class=\"line\"></span> <span class=\"line\"></span> <span\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"line\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div> <span style=\"font-weight: 500; color: #74afc9;\">전체메뉴</span>\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t</nav>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"full-menu bg-white\">\r\n");
      out.write("\t\t\t\t\t<div class=\"inner\">\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"full-list inner cf\">\r\n");
      out.write("\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div>병원안내</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<ol>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"/jiksan/about-clinic\">병원안내</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"/jiksan/about-services\">진료안내</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"/jiksan/about-team\">의료진 소개</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"/jiksan/contact-us\">오시는길</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t</ol>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div>당뇨클리닉</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<ol>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"/jiksan/diabetes\">당뇨병이란?</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"/jiksan/diabetes-test\">당뇨병 검사</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"/jiksan/diabetes-diet\">당뇨병과 식생활</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"/jiksan/diabetes-exercise\">당뇨병과 운동</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"/jiksan/diabetes-complications\">당뇨병 합병증</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t</ol>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div>건강정보</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<ol>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"/jiksan/about-disease\">질환백과</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t</ol>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div>진료 예약</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<ol>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"#\">예약안내</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"/jiksan/views/user/userReservation.jsp\">진료\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t예약하기</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t</ol>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div>커뮤니티</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<ol>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"/jiksan/views/notice/nlist\">공지사항</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"/jiksan/views/faq/faqlist\">자주묻는 질문</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"#\">Q&A 게시판</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t</ol>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t");
 } else if (loginUser != null && loginUser.getUserLv() > '1'){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t<!-- 관리자가 로그인했다면 -->\r\n");
      out.write("\t\t\t\t\t<nav>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"/jiksan/logout\"><img\r\n");
      out.write("\t\t\t\t\t\t\tsrc=\"/jiksan/resources/main_images/nav-icon01.png\" alt=\"LOGOUT\"><span>LOGOUT</span></a>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"/jiksan/views/user/userMyPage.jsp\"><img\r\n");
      out.write("\t\t\t\t\t\t\tsrc=\"/jiksan/resources/main_images/nav-icon02.png\" alt=\"MY PAGE\"><span>MY\r\n");
      out.write("\t\t\t\t\t\t\t\tPAGE</span></a> <a href=\"/jiksan/views/user/userReservation.jsp\"><img\r\n");
      out.write("\t\t\t\t\t\t\tsrc=\"/jiksan/resources/main_images/nav-icon04.png\"\r\n");
      out.write("\t\t\t\t\t\t\talt=\"RESERVATION\"><span>RESERVATION</span></a> <a href=\"#n\"\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"full-slide\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"three col\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"hamburger\" id=\"hamburger-1\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"line\"></span> <span class=\"line\"></span> <span\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tclass=\"line\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div> <span style=\"font-weight: 500; color: #74afc9;\">전체메뉴</span>\r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t</nav>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"full-menu bg-white\">\r\n");
      out.write("\t\t\t\t\t<div class=\"inner\">\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"full-list inner cf\">\r\n");
      out.write("\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div>병원안내</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<ol>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"/jiksan/about-clinic\">병원안내</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"/jiksan/about-services\">진료안내</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"/jiksan/about-team\">의료진 소개</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"/jiksan/contact-us\">오시는길</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t</ol>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div>당뇨클리닉</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<ol>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"/jiksan/diabetes\">당뇨병이란?</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"/jiksan/diabetes-test\">당뇨병 검사</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"/jiksan/diabetes-diet\">당뇨병과 식생활</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"/jiksan/diabetes-exercise\">당뇨병과 운동</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"/jiksan/diabetes-complications\">당뇨병 합병증</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t</ol>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div>건강정보</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<ol>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"/jiksan/about-disease\">질환백과</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t</ol>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div>진료 예약 관리</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<ol>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"#\">예약안내</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"/jiksan/views/user/userReservation.jsp\">진료\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t예약하기</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t</ol>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div>커뮤니티 관리</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<ol>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"/jiksan/views/notice/nlist\">공지사항</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"/jiksan/views/faq/faqlist\">자주묻는 질문</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"#\">Q&A 게시판</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t</ol>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div>회원 관리</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<ol>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"#\">회원 리스트</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"#\">#</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"#\">#</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t</ol>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t");
 } else { 
      out.write("\r\n");
      out.write("\t\t\t\t<!-- 환자가 로그인했다면 -->\r\n");
      out.write("\t\t\t\t<nav>\r\n");
      out.write("\t\t\t\t\t<a href=\"/jiksan/logout\"><img\r\n");
      out.write("\t\t\t\t\t\tsrc=\"/jiksan/resources/main_images/nav-icon01.png\" alt=\"LOGOUT\"><span>LOGOUT</span></a>\r\n");
      out.write("\t\t\t\t\t<a href=\"/jiksan/views/user/userMyPage.jsp\"><img\r\n");
      out.write("\t\t\t\t\t\tsrc=\"/jiksan/resources/main_images/nav-icon02.png\" alt=\"MY PAGE\"><span>MY\r\n");
      out.write("\t\t\t\t\t\t\tPAGE</span></a> <a href=\"/jiksan/views/user/userReservation.jsp\"><img\r\n");
      out.write("\t\t\t\t\t\tsrc=\"/jiksan/resources/main_images/nav-icon04.png\"\r\n");
      out.write("\t\t\t\t\t\talt=\"RESERVATION\"><span>RESERVATION</span></a> <a href=\"#n\"\r\n");
      out.write("\t\t\t\t\t\tclass=\"full-slide\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"three col\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"hamburger\" id=\"hamburger-1\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"line\"></span> <span class=\"line\"></span> <span\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"line\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div> <span style=\"font-weight: 500; color: #74afc9;\">전체메뉴</span>\r\n");
      out.write("\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t</nav>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"full-menu bg-white\">\r\n");
      out.write("\t\t\t<div class=\"inner\">\r\n");
      out.write("\t\t\t\t<ul class=\"full-list inner cf\">\r\n");
      out.write("\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t<div>병원안내</div>\r\n");
      out.write("\t\t\t\t\t\t<ol>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"/jiksan/about-clinic\">병원안내</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"/jiksan/about-services\">진료안내</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"/jiksan/about-team\">의료진 소개</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"/jiksan/contact-us\">오시는길</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ol>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t<div>당뇨클리닉</div>\r\n");
      out.write("\t\t\t\t\t\t<ol>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"/jiksan/diabetes\">당뇨병이란?</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"/jiksan/diabetes-test\">당뇨병 검사</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"/jiksan/diabetes-diet\">당뇨병과 식생활</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"/jiksan/diabetes-exercise\">당뇨병과 운동</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"/jiksan/diabetes-complications\">당뇨병 합병증</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ol>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t<div>건강정보</div>\r\n");
      out.write("\t\t\t\t\t\t<ol>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"/jiksan/about-disease\">질환백과</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</ol>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t<div>진료 예약</div>\r\n");
      out.write("\t\t\t\t\t\t<ol>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\">예약안내</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"/jiksan/views/user/userReservation.jsp\">진료\r\n");
      out.write("\t\t\t\t\t\t\t\t\t예약하기</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</ol>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t<div>커뮤니티</div>\r\n");
      out.write("\t\t\t\t\t\t<ol>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"/jiksan/views/notice/nlist\">공지사항</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"/jiksan/views/faq/faqlist\">자주묻는 질문</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\">Q&A 게시판</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</ol>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t</section>\r\n");
      out.write("\t\t</header>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<hr>\r\n");
      out.write("<h1>FAQ 자주 묻는 질문</h1>\r\n");
      out.write("<br>\r\n");
      out.write("<h2 align=\"center\">새 FAQ 등록 페이지</h2>\r\n");
      out.write("<br>\r\n");
      out.write("<form action=\"/jiksan/faqinsert\" method=\"post\">\r\n");
      out.write("<!-- <table align=\"center\" width=\"500\" border=\"1\" cellspacing=\"0\" cellpadding=\"5\">\r\n");
      out.write("<tr><th>제 목</th><td><input type=\"text\" name=\"title\" size=\"78\"></td></tr>\r\n");
      out.write("<tr><th>내 용</th><td><textarea rows=\"10\" cols=\"80\" name=\"text\"></textarea></td></tr>\r\n");
      out.write("<tr><th colspan=\"2\">\r\n");
      out.write("\t<input type=\"submit\" value=\"등록하기\"> &nbsp; \r\n");
      out.write("\t<input type=\"reset\" value=\"작성취소\"> &nbsp; \r\n");
      out.write("\t<input type=\"button\" value=\"목록\" onclick=\"javascript:history.go(-1); return false;\"></th></tr>\r\n");
      out.write("</table>  -->\r\n");
      out.write("<div align=\"center\">\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("\t<p>제목 : <input type=\"text\" name=\"faq_title\" size=\"78\"> </p> \r\n");
      out.write("\t<p>내용 : <textarea rows=\"10\" cols=\"80\" name=\"faq_text\"></textarea></p>\r\n");
      out.write("\t<input type=\"submit\" value=\"등록하기\"> &nbsp; \r\n");
      out.write("\t<input type=\"reset\" value=\"작성취소\" onclick=\"javascript:history.go(-1); return false;\"> &nbsp; \r\n");
      out.write("\t<input type=\"button\" value=\"목록\" onclick=\"javascript:history.go(-1); return false;\">\r\n");
      out.write("</div> \r\n");
      out.write("\r\n");
      out.write("</form>\r\n");
      out.write("\r\n");
      out.write("<hr>\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("footer {\r\n");
      out.write("\tbackground:#3e4247;\r\n");
      out.write("\ttext-align : center;\r\n");
      out.write("\twidth : 100%;\r\n");
      out.write("\theight : 10%;\r\n");
      out.write("\tcolor: #d1d1d1;\r\n");
      out.write("\tfont-size : 0.8em;\r\n");
      out.write("\tpadding-top : 2%;\t\r\n");
      out.write("\tpadding-bottom : 2%;\t\r\n");
      out.write("\tline-height:1;\r\n");
      out.write("}\r\n");
      out.write("footer div h3 {\r\n");
      out.write("\tcolor: #fff;\r\n");
      out.write("\tfont-size : 1.2em;\r\n");
      out.write("\tfont-weight : none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".footer_btn_list li {\r\n");
      out.write(" float: auto; overflow: hidden;\r\n");
      out.write(" padding-right: 10px;\r\n");
      out.write(" display:inline;\r\n");
      out.write(" line-height:2;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#copyright, .footer_btn_list, address{\r\n");
      out.write("\tcolor: #9AA0A6 /* #80868B */\r\n");
      out.write("} \r\n");
      out.write("hr { clear : both; }\r\n");
      out.write("</style>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\t//개인정보처리방침\r\n");
      out.write("\tfunction OpenMemberPrivate() { // \"개인정보처리방침\" 만들기? 가져오기\r\n");
      out.write("\t\twindow.open(\r\n");
      out.write("\t\t\t\t\t\t\"/jiksan/resources/js/개인정보처리방침.asp\",\r\n");
      out.write("\t\t\t\t\t\t\"MemberPrivate\",\r\n");
      out.write("\t\t\t\t\t\t\"toolbar=0, left=100, top=50, location=0, directories=0, status=0, menubar=0, scrollbars=1, resizable=0, copyhistory=0, width=600 ,height=600\");\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<footer>\r\n");
      out.write("<div>\r\n");
      out.write("\t\t\t\t<h3>직산 가정의학과 의원 Jiksan Family Medicine Clinic</h3><br>\r\n");
      out.write("\t\t\t\t<address>충남 천안시 서북구 직산읍 직산로 31 직산농협 2층 &nbsp;&nbsp;&nbsp;&nbsp; (041) 583-8500\r\n");
      out.write("\t\t\t\t</address>\r\n");
      out.write("\t\t\t\t<br> <br>\r\n");
      out.write("\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t평일 08:30 ~ 18:00 &nbsp;&nbsp;&nbsp;&nbsp; 토요일 09:00 ~ 13:00\r\n");
      out.write("\t\t\t\t\t&nbsp;&nbsp;&nbsp;&nbsp; 점심시간 13:00 ~ 14:00\r\n");
      out.write("\t\t\t\t\t&nbsp;&nbsp;&nbsp;&nbsp; 화요일 야간진료 21:00 까지 &nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t\t<i>일요일/공휴일은 휴무입니다.</i>\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t<label id=\"copyright\">Copyright ⓒ 2020 by Jiksan Family Medicine Clinic. All rights reserved.</label>\r\n");
      out.write("\t\t\t\t<br>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\t<ul class=\"footer_btn_list\">\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\" onclick=\"OpenMemberPrivate();\" style=\"cursor: pointer;\">개인정보처리방침</a></li>\r\n");
      out.write("\t\t\t\t\t<li> | </li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">이용약관</a></li>\r\n");
      out.write("\t\t\t\t\t<li> | </li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"/jiksan/contact-us\">찾아오시는길</a></li>\t\t\t");
      out.write("\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("</footer>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
