/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.43
 * Generated at: 2021-01-04 05:47:54 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class directions_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>direction</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("   <!--\r\n");
      out.write("   * Daum 지도 - 약도서비스\r\n");
      out.write("   * 한 페이지 내에 약도를 2개 이상 넣을 경우에는\r\n");
      out.write("   * 약도의 수 만큼 소스를 새로 생성, 삽입해야 합니다.\r\n");
      out.write("-->\r\n");
      out.write("<!-- 1. 약도 노드 -->\r\n");
      out.write("<div id=\"daumRoughmapContainer1522126832636\" class=\"root_daum_roughmap root_daum_roughmap_landing\"></div>\r\n");
      out.write("\r\n");
      out.write("<!-- 2. 설치 스크립트 -->\r\n");
      out.write("<script charset=\"UTF-8\" class=\"daum_roughmap_loader_script\" src=\"http://dmaps.daum.net/map_js_init/roughmapLoader.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- 3. 실행 스크립트 -->\r\n");
      out.write("<script charset=\"UTF-8\">\r\n");
      out.write("   new daum.roughmap.Lander({\r\n");
      out.write("      \"timestamp\" : \"1522126832636\",\r\n");
      out.write("      \"key\" : \"ndvi\",\r\n");
      out.write("      \"mapWidth\" : \"700\",\r\n");
      out.write("      \"mapHeight\" : \"300\"\r\n");
      out.write("   }).render();\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("   <!-- 연락처 -->\r\n");
      out.write("   <div class=\"guide_table\">\r\n");
      out.write("      <h3>연락처</h3>\r\n");
      out.write("      <table>\r\n");
      out.write("         <caption>연락처에 설명입니다.</caption> \r\n");
      out.write("         <colgroup>\r\n");
      out.write("         <col width=\"20%\">\r\n");
      out.write("         <col width=\"auto\">\r\n");
      out.write("         </colgroup>\r\n");
      out.write("         <tbody>\r\n");
      out.write("\r\n");
      out.write("            <tr>\r\n");
      out.write("               <th>주소</th>\r\n");
      out.write("               <td>충남 천안시 동남구 일봉로 8 (신방동, 학산빌딩) 3층</td>\r\n");
      out.write("            </tr>\r\n");
      out.write("\r\n");
      out.write("            <tr>\r\n");
      out.write("               <th>전화번호</th>\r\n");
      out.write("               <td>041-573-5595</td>\r\n");
      out.write("            </tr>\r\n");
      out.write("\r\n");
      out.write("            <tr>\r\n");
      out.write("               <th>팩스</th>\r\n");
      out.write("               <td>041-573-9986</td>\r\n");
      out.write("            </tr>\r\n");
      out.write("\r\n");
      out.write("         </tbody>\r\n");
      out.write("      </table>\r\n");
      out.write("   </div>\r\n");
      out.write("   <!-- /연락처 -->\r\n");
      out.write("\r\n");
      out.write("         </tbody>\r\n");
      out.write("      </table>\r\n");
      out.write("   </div>\r\n");
      out.write("   <!-- /교통편 안내 -->\r\n");
      out.write("</div>\r\n");
      out.write("<!-- 찾아오시는길 -->\r\n");
      out.write("                     </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("               </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- container E -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("//개인정보처리방침\r\n");
      out.write("function OpenMemberPrivate() {\r\n");
      out.write("   window.open(\"/Module/Member/PrivatePopUp.asp\", \"MemberPrivate\", \"toolbar=0, left=100, top=50, location=0, directories=0, status=0, menubar=0, scrollbars=1, resizable=0, copyhistory=0, width=600 ,height=600\");\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("      <!-- footer S -->\r\n");
      out.write("      <div class=\"footer\">\r\n");
      out.write("         <div class=\"contents\">\r\n");
      out.write("            <div class=\"address\">\r\n");
      out.write("               <ul class=\"footer_btn_list\">\r\n");
      out.write("                  <li><a href=\"#\" onclick=\"OpenMemberPrivate();\" style=\"cursor:pointer;\">개인정보처리방침</a></li>\r\n");
      out.write("                  <li><a href=\"#\">이용약관</a></li>\r\n");
      out.write("                  <li><a href=\"/Module/Intro/GuideView.asp\">찾아오시는길</a></li>\r\n");
      out.write("               </ul>\r\n");
      out.write("               <address>\r\n");
      out.write("                  충남 천안시 동남구 일봉로 8 (신방동, 학산빌딩) 3층 &nbsp;한사랑가정의학과의원 TEL.041-573-5595&nbsp;FAX.041-573-9986&nbsp;&nbsp;\r\n");
      out.write("               </address>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("         <!-- banner S -->\r\n");
      out.write("         <div class=\"footer_banner\">\r\n");
      out.write("            <ul class=\"list\">\r\n");
      out.write("               <li><div id=\"rolling2\"></div></li>\r\n");
      out.write("               <li><div id=\"rolling1\"></div></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("         </div>\r\n");
      out.write("         <!-- banner E -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("         </div>\r\n");
      out.write("       </div>\r\n");
      out.write("      <!-- footer E -->\r\n");
      out.write("   </div>\r\n");
      out.write("   <!-- Wrap E -->\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("한사랑 가정의학과 복붙하고 아직 안고쳤어");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
