/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.43
 * Generated at: 2021-01-07 23:20:47 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.disease;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.ArrayList;
import disease.model.vo.Disease;
import user.model.vo.User;

public final class diseaseListView_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/views/disease/../common/header.jsp", Long.valueOf(1610060468650L));
    _jspx_dependants.put("/views/disease/../common/footer.jsp", Long.valueOf(1610060554004L));
    _jspx_dependants.put("/views/disease/../common/menubar.jsp", Long.valueOf(1610036932113L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("user.model.vo.User");
    _jspx_imports_classes.add("java.util.ArrayList");
    _jspx_imports_classes.add("disease.model.vo.Disease");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			"./views/common/error.jsp", true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

   ArrayList<Disease> list = (ArrayList<Disease>)request.getAttribute("list");
 	int listCount = ((Integer)request.getAttribute("listCount")).intValue();
	int maxPage = ((Integer)request.getAttribute("maxPage")).intValue();
	int startPage = ((Integer)request.getAttribute("startPage")).intValue();
	int endPage = ((Integer)request.getAttribute("endPage")).intValue();
	int currentPage = ((Integer)request.getAttribute("currentPage")).intValue();
	String category = (String)request.getAttribute("category");
	String keyword = (String)request.getAttribute("keyword");
	
	Disease disease = new Disease();

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>건강정보(질환백과): 목록보기</title>\r\n");
      out.write("\r\n");
      out.write("<!-- <link rel=\"stylesheet\" type=\"text/css\" href=\"/jiksan/resources/css/jiksan-disease.css\"/>% -->\r\n");
      out.write("<script type = \"text/javascript\" src = \"/jiksan/resources/js/jquery-3.5.1.min.js\"></script>\r\n");
      out.write("<script type = \"text/javascript\">/* https://stackoverflow.com/questions/8661498/on-image-hover-display-title-alt-tag-in-center */\r\n");
      out.write("\t\t$('table a img').hover(\r\n");
      out.write("\t\t\t    function(){\r\n");
      out.write("\t\t\t        $(this).css('opacity','.5');\r\n");
      out.write("\t\t\t        var a = $(this).attr('alt');\r\n");
      out.write("\t\t\t        $(this).parent().append('<div class=\"title\">' + a + '</div>');\r\n");
      out.write("\t\t\t    },\r\n");
      out.write("\t\t\t    function(){\r\n");
      out.write("\t\t\t        $(this).css('opacity','1');\r\n");
      out.write("\t\t\t        $(this).next().remove('.title');\r\n");
      out.write("\t\t\t    }\r\n");
      out.write("\t\t\t);\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\tfunction getDisNo(disease_no){\r\n");
      out.write("\t\t\tlocation.href='/jiksan/disease?disease_no=' + disease_no;\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("</script>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("table a img{\r\n");
      out.write("    position:relative;\r\n");
      out.write("}\r\n");
      out.write(".gallery{\r\n");
      out.write("    position:absolute;\r\n");
      out.write("    z-index:1000;\r\n");
      out.write("    top:50%;\r\n");
      out.write("    bottom:50%;\r\n");
      out.write("    right:50%;\r\n");
      out.write("    left:50%;\r\n");
      out.write("    width:100px;\r\n");
      out.write("    border-radius:5px;\r\n");
      out.write("    background: white;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=no, target-densitydpi=medium-dpi\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"/jiksan/resources/css/jiksan-sidebar.css\"/>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write('\r');
      out.write('\n');
   User loginUser = (User)session.getAttribute("loginUser"); 
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\"    href=\"/jiksan/resources/css/jiksan-header.css\" />\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("   src=\"/jiksan/resources/js/jquery-3.5.1.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("$(document).ready(function(){\r\n");
      out.write("   $(\".full-slide\").click(function() {\r\n");
      out.write("      $(\".full-menu\").stop().slideToggle(300);\r\n");
      out.write("         $('.hamburger .line').css('transition', 'all 0.2s ease-in-out');\r\n");
      out.write("\r\n");
      out.write("         if($('.hamburger').hasClass('is-active')){\r\n");
      out.write("            $('.hamburger span:nth-child(1)').css({'transform':'translateY(0) rotate(0)'});\r\n");
      out.write("            $('.hamburger span:nth-child(2)').css({'opacity':'1'});\r\n");
      out.write("            $('.hamburger span:nth-child(3)').css({'transform':'translateY(0) rotate(0)'});            \r\n");
      out.write("            $('.hamburger').removeClass('is-active');\r\n");
      out.write("         } else {\r\n");
      out.write("            $('.hamburger span:nth-child(1)').css({'transform':'translateY(12px) rotate(45deg)'});\r\n");
      out.write("            $('.hamburger span:nth-child(2)').css({'opacity':'0'});\r\n");
      out.write("            $('.hamburger span:nth-child(3)').css({'transform':'translateY(-4px) rotate(-45deg)'});\r\n");
      out.write("            $('.hamburger').addClass('is-active');\r\n");
      out.write("         }\r\n");
      out.write("    });\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("   function setCookie(name, value, expiredays) {\r\n");
      out.write("      var todayDate = new Date();\r\n");
      out.write("      todayDate.setDate(todayDate.getDate() + expiredays);\r\n");
      out.write("      document.cookie = name + \"=\" + escape(value) + \"; path=/; expires=\" + todayDate.toGMTString() + \";\"\r\n");
      out.write("   }\r\n");
      out.write("   function getCookie(name) {\r\n");
      out.write("      var nameOfCookie = name + \"=\";\r\n");
      out.write("      var x = 0;\r\n");
      out.write("      while (x <= document.cookie.length) {\r\n");
      out.write("         var y = (x + nameOfCookie.length);\r\n");
      out.write("         if (document.cookie.substring(x, y) == nameOfCookie) {\r\n");
      out.write("            if ((endOfCookie = document.cookie.indexOf(\";\", y)) == -1)\r\n");
      out.write("               endOfCookie = document.cookie.length;\r\n");
      out.write("            return unescape(document.cookie.substring(y, endOfCookie));\r\n");
      out.write("         }\r\n");
      out.write("         x = document.cookie.indexOf(\" \", x) + 1;\r\n");
      out.write("         if (x == 0)\r\n");
      out.write("            break;\r\n");
      out.write("      }\r\n");
      out.write("      return \"\";\r\n");
      out.write("   }\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("        function redirect(){\r\n");
      out.write("        window.location.href = \"/jiksan/drlist\"\r\n");
      out.write("        }\r\n");
      out.write("        function redirectAdmin(){\r\n");
      out.write("        window.location.href = \"/jiksan/drlist.ad\"\r\n");
      out.write("        }\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("   <div id=\"wrap\" class=\"mw1600\" style=\"position: relative;\">\r\n");
      out.write("      <div class=\"mw1600\">\r\n");
      out.write("         <header class=\"bg-white mw\">\r\n");
      out.write("            <div id=\"header-wrap\" class=\"inner cf\">\r\n");
      out.write("               <a href=\"/jiksan/index.jsp\"><img\r\n");
      out.write("                  src=\"/jiksan/resources/main_images/jiksan_logo.png\"\r\n");
      out.write("                  alt=\"직산 가정의학과 의원\" style=\"width: auto; max-width: 22%\"></a>\r\n");
      out.write("\r\n");
      out.write("               <section>\r\n");
      out.write("                  ");
      out.write("\r\n");
      out.write("                  ");
 if(loginUser == null){ 
      out.write("\r\n");
      out.write("                  <nav>\r\n");
      out.write("                     <a href=/jiksan/views/user/userLogin.jsp><img\r\n");
      out.write("                        src=\"/jiksan/resources/main_images/nav-icon01.png\" alt=\"LOGIN\"><span>LOGIN</span></a>\r\n");
      out.write("                     <a href=\"/jiksan/views/user/userEnroll.jsp\"><img\r\n");
      out.write("                        src=\"/jiksan/resources/main_images/nav-icon02.png\" alt=\"JOIN\"><span>JOIN</span></a>\r\n");
      out.write("                     <a href=\"/jiksan/views/about/contact-us.jsp\"><img\r\n");
      out.write("                        src=\"/jiksan/resources/main_images/nav-icon03.png\"\r\n");
      out.write("                        alt=\"CONTACT US\"><span>CONTACT US</span></a> <a href=\"#n\"\r\n");
      out.write("                        class=\"full-slide\">\r\n");
      out.write("                        <div class=\"row\">\r\n");
      out.write("                           <div class=\"three col\">\r\n");
      out.write("                              <div class=\"hamburger\" id=\"hamburger-1\">\r\n");
      out.write("                                 <span class=\"line\"></span> <span class=\"line\"></span> <span\r\n");
      out.write("                                    class=\"line\"></span>\r\n");
      out.write("                              </div>\r\n");
      out.write("                           </div>\r\n");
      out.write("                        </div> <span style=\"font-weight: 500; color: #74afc9;\">전체메뉴</span>\r\n");
      out.write("                     </a>\r\n");
      out.write("                  </nav>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"full-menu bg-white\">\r\n");
      out.write("               <div class=\"inner\">\r\n");
      out.write("                  <ul class=\"full-list inner cf\">\r\n");
      out.write("                     <li>\r\n");
      out.write("                        <div>병원안내</div>\r\n");
      out.write("                        <ol>\r\n");
      out.write("                           <li><a href=\"/jiksan/views/about/about-clinic.jsp\">병원안내</a></li>\r\n");
      out.write("                           <li><a href=\"/jiksan/views/about/about-services.jsp\">진료안내</a></li>\r\n");
      out.write("                           <li><a href=\"/jiksan/views/about/about-team.jsp\">의료진 소개</a></li>\r\n");
      out.write("                           <li><a href=\"/jiksan/views/about/contact-us.jsp\">오시는길</a></li>\r\n");
      out.write("                        </ol>\r\n");
      out.write("                     </li>\r\n");
      out.write("                     <li>\r\n");
      out.write("                        <div>당뇨클리닉</div>\r\n");
      out.write("                        <ol>\r\n");
      out.write("                           <li><a href=\"/jiksan/disease?disease_no=108\">당뇨병이란?</a></li>\r\n");
      out.write("                           <li><a href=\"/jiksan/views/diabetes/diabetes-diet.jsp\">당뇨병과 식생활</a></li>\r\n");
      out.write("                           <li><a href=\"/jiksan/views/diabetes/diabetes-exercise.jsp\">당뇨병과 운동</a></li>\r\n");
      out.write("                           <li><a href=\"/jiksan/disease?disease_no=108#complications\">당뇨병 합병증</a></li>\r\n");
      out.write("                        </ol>\r\n");
      out.write("                     </li>\r\n");
      out.write("                     <li>\r\n");
      out.write("                        <div>건강정보</div>\r\n");
      out.write("                        <ol>\r\n");
      out.write("                           <li><a href=\"/jiksan/dlist\">질환백과</a></li>\r\n");
      out.write("                           ");
      out.write("\r\n");
      out.write("                        </ol>\r\n");
      out.write("                     </li>\r\n");
      out.write("                     <li>\r\n");
      out.write("                        <div>진료 예약</div>\r\n");
      out.write("                        <ol>\r\n");
      out.write("                           <li><a href=\"/jiksan/views/reservation/about-appt.jsp\">예약안내</a></li>\r\n");
      out.write("                           <li><a href=\"javascript:redirect()\">진료 예약하기</a></li>\r\n");
      out.write("                           ");
      out.write("\r\n");
      out.write("                        </ol>\r\n");
      out.write("                     </li>\r\n");
      out.write("                     <li>\r\n");
      out.write("                        <div>커뮤니티</div>\r\n");
      out.write("                        <ol>\r\n");
      out.write("                           <li><a href=\"/jiksan/nlist\">공지사항</a></li>\r\n");
      out.write("                           <li><a href=\"/jiksan/faqlist\">자주묻는 질문</a></li>\r\n");
      out.write("                           <li><a href=\"/jiksan/qalist\">Q&A 게시판</a></li>\r\n");
      out.write("                           ");
      out.write("\r\n");
      out.write("                           ");
      out.write("\r\n");
      out.write("                        </ol>\r\n");
      out.write("                     </li>\r\n");
      out.write("                  </ul>\r\n");
      out.write("               </div>\r\n");
      out.write("               ");
 } else if (loginUser != null && loginUser.getUserLv() > '1'){ 
      out.write("\r\n");
      out.write("               <nav >\r\n");
      out.write("                  <a href=\"/jiksan/logout\"><img\r\n");
      out.write("                     src=\"/jiksan/resources/main_images/nav-icon01.png\" alt=\"LOGOUT\"><span>LOGOUT</span></a>\r\n");
      out.write("                  <a href=\"/jiksan/views/user/userMyPage.jsp\">\r\n");
      out.write("                  ");
      out.write("\r\n");
      out.write("                     <img src=\"/jiksan/resources/main_images/nav-icon02.png\" alt=\"MY PAGE\"><span>MY PAGE</span></a>\r\n");
      out.write("                  <a href=\"javascript:redirectAdmin()\"><img\r\n");
      out.write("                     src=\"/jiksan/resources/main_images/nav-icon04.png\"\r\n");
      out.write("                     alt=\"RESERVATION\"><span>RESERVATION</span></a> <a href=\"#n\"\r\n");
      out.write("                     class=\"full-slide\">\r\n");
      out.write("                     <div class=\"row\">\r\n");
      out.write("                        <div class=\"three col\">\r\n");
      out.write("                           <div class=\"hamburger\" id=\"hamburger-1\">\r\n");
      out.write("                              <span class=\"line\"></span> <span class=\"line\"></span> <span\r\n");
      out.write("                                 class=\"line\"></span>\r\n");
      out.write("                           </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                     </div> <span style=\"font-weight: 500; color: #74afc9;\">전체메뉴</span>\r\n");
      out.write("                  </a>\r\n");
      out.write("               </nav>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"full-menu bg-white\">\r\n");
      out.write("               <div class=\"inner\">\r\n");
      out.write("                  <ul class=\"full-list inner cf\">\r\n");
      out.write("                     <li>\r\n");
      out.write("                        <div>병원안내</div>\r\n");
      out.write("                        <ol>\r\n");
      out.write("                           <li><a href=\"/jiksan/views/about/about-clinic.jsp\">병원안내</a></li>\r\n");
      out.write("                           <li><a href=\"/jiksan/views/about/about-services.jsp\">진료안내</a></li>\r\n");
      out.write("                           <li><a href=\"/jiksan/views/about/about-team.jsp\">의료진 소개</a></li>\r\n");
      out.write("                           <li><a href=\"/jiksan/views/about/contact-us.jsp\">오시는길</a></li>\r\n");
      out.write("                        </ol>\r\n");
      out.write("                     </li>\r\n");
      out.write("                     <li>\r\n");
      out.write("                        <div>당뇨클리닉</div>\r\n");
      out.write("                        <ol>\r\n");
      out.write("                           <li><a href=\"/jiksan/disease?disease_no=108\">당뇨병이란?</a></li>\r\n");
      out.write("                           <li><a href=\"/jiksan/views/diabetes/diabetes-diet.jsp\">당뇨병과 식생활</a></li>\r\n");
      out.write("                           <li><a href=\"/jiksan/views/diabetes/diabetes-exercise.jsp\">당뇨병과 운동</a></li>\r\n");
      out.write("                           <li><a href=\"/jiksan/disease?disease_no=108#complications\">당뇨병 합병증</a></li>\r\n");
      out.write("                        </ol>\r\n");
      out.write("                     </li>\r\n");
      out.write("                     <li>\r\n");
      out.write("                        <div>건강정보 관리</div>\r\n");
      out.write("                        <ol>\r\n");
      out.write("                           <li><a href=\"/jiksan/dlist\">질환백과</a></li>\r\n");
      out.write("                           ");
      out.write("\r\n");
      out.write("                        </ol>\r\n");
      out.write("                     </li>\r\n");
      out.write("                     <li>\r\n");
      out.write("                        <div>진료 예약 관리</div>\r\n");
      out.write("                        <ol>\r\n");
      out.write("                           <li><a href=\"/jiksan/views/reservation/about-appt.jsp\">예약안내</a></li>\r\n");
      out.write("                           <li><a href=\"/jiksan/reservation\">진료 예약하기</a></li>\r\n");
      out.write("                           ");
      out.write("\r\n");
      out.write("                        </ol>\r\n");
      out.write("                     </li>\r\n");
      out.write("                     <li>\r\n");
      out.write("                        <div>커뮤니티 관리</div>\r\n");
      out.write("                        <ol>\r\n");
      out.write("                           <li><a href=\"/jiksan/nlist\">공지사항</a></li>\r\n");
      out.write("                           <li><a href=\"/jiksan/faqlist\">자주묻는 질문</a></li>\r\n");
      out.write("                           <li><a href=\"/jiksan/qalist\">Q&A 게시판</a></li>\r\n");
      out.write("                           ");
      out.write("\r\n");
      out.write("                           ");
      out.write("\r\n");
      out.write("                        </ol>\r\n");
      out.write("                     </li>\r\n");
      out.write("                     <li>\r\n");
      out.write("                        <div>회원 관리</div>\r\n");
      out.write("                        <ol>\r\n");
      out.write("                           <li><a href=\"#\">회원 리스트</a></li>\r\n");
      out.write("                           <li><a href=\"#\">#</a></li>\r\n");
      out.write("                           <li><a href=\"#\">#</a></li>\r\n");
      out.write("                        </ol>\r\n");
      out.write("                     </li>\r\n");
      out.write("                  </ul>\r\n");
      out.write("               </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            ");
 } else { 
      out.write("\r\n");
      out.write("            <nav>\r\n");
      out.write("               <a href=\"/jiksan/logout\"><img\r\n");
      out.write("                  src=\"/jiksan/resources/main_images/nav-icon01.png\" alt=\"LOGOUT\"><span>LOGOUT</span></a>\r\n");
      out.write("                  <a href=\"/jiksan/views/user/userMyPage.jsp\">\r\n");
      out.write("                  ");
      out.write("\r\n");
      out.write("                     <img src=\"/jiksan/resources/main_images/nav-icon02.png\" alt=\"MY PAGE\"><span>MY PAGE</span></a>\r\n");
      out.write("                  <a href=\"javascript:redirect()\"><img\r\n");
      out.write("                  src=\"/jiksan/resources/main_images/nav-icon04.png\"\r\n");
      out.write("                  alt=\"RESERVATION\"><span>RESERVATION</span></a> <a href=\"#n\"\r\n");
      out.write("                  class=\"full-slide\">\r\n");
      out.write("                  <div class=\"row\">\r\n");
      out.write("                     <div class=\"three col\">\r\n");
      out.write("                        <div class=\"hamburger\" id=\"hamburger-1\">\r\n");
      out.write("                           <span class=\"line\"></span> <span class=\"line\"></span> <span\r\n");
      out.write("                              class=\"line\"></span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                     </div>\r\n");
      out.write("                  </div> <span style=\"font-weight: 500; color: #74afc9;\">전체메뉴</span>\r\n");
      out.write("               </a>\r\n");
      out.write("            </nav>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"full-menu bg-white\">\r\n");
      out.write("         <div class=\"inner\">\r\n");
      out.write("            <ul class=\"full-list inner cf\">\r\n");
      out.write("               <li>\r\n");
      out.write("                  <div>병원안내</div>\r\n");
      out.write("                  <ol>\r\n");
      out.write("                           <li><a href=\"/jiksan/views/about/about-clinic.jsp\">병원안내</a></li>\r\n");
      out.write("                           <li><a href=\"/jiksan/views/about/about-services.jsp\">진료안내</a></li>\r\n");
      out.write("                           <li><a href=\"/jiksan/views/about/about-team.jsp\">의료진 소개</a></li>\r\n");
      out.write("                           <li><a href=\"/jiksan/views/about/contact-us.jsp\">오시는길</a></li>\r\n");
      out.write("                  </ol>\r\n");
      out.write("               </li>\r\n");
      out.write("               <li>\r\n");
      out.write("                  <div>당뇨클리닉</div>\r\n");
      out.write("                  <ol>\r\n");
      out.write("                           <li><a href=\"/jiksan/disease?disease_no=108\">당뇨병이란?</a></li>\r\n");
      out.write("                           <li><a href=\"/jiksan/views/diabetes/diabetes-diet.jsp\">당뇨병과 식생활</a></li>\r\n");
      out.write("                           <li><a href=\"/jiksan/views/diabetes/diabetes-exercise.jsp\">당뇨병과 운동</a></li>\r\n");
      out.write("                           <li><a href=\"/jiksan/disease?disease_no=108#complications\">당뇨병 합병증</a></li>\r\n");
      out.write("                  </ol>\r\n");
      out.write("               </li>\r\n");
      out.write("               <li>\r\n");
      out.write("                  <div>건강정보</div>\r\n");
      out.write("                  <ol>\r\n");
      out.write("                     <li><a href=\"/jiksan/dlist\">질환백과</a></li>\r\n");
      out.write("                     ");
      out.write("\r\n");
      out.write("                  </ol>\r\n");
      out.write("               </li>\r\n");
      out.write("               <li>\r\n");
      out.write("                  <div>진료 예약</div>\r\n");
      out.write("                  <ol>\r\n");
      out.write("                     <li><a href=\"/jiksan/views/reservation/about-appt.jsp\">예약안내</a></li>\r\n");
      out.write("                     <li><a href=\"javascript:redirectAdmin()\">진료 예약하기</a></li>\r\n");
      out.write("                     ");
      out.write("\r\n");
      out.write("                  </ol>\r\n");
      out.write("               </li>\r\n");
      out.write("               <li>\r\n");
      out.write("                  <div>커뮤니티</div>\r\n");
      out.write("                  <ol>\r\n");
      out.write("                     <li><a href=\"/jiksan/nlist\">공지사항</a></li>\r\n");
      out.write("                     <li><a href=\"/jiksan/faqlist\">자주묻는 질문</a></li>\r\n");
      out.write("                     <li><a href=\"/jiksan/qalist\">Q&A 게시판</a></li>\r\n");
      out.write("                     ");
      out.write("\r\n");
      out.write("                     ");
      out.write("\r\n");
      out.write("                  </ol>\r\n");
      out.write("               </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("         </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      ");
 } 
      out.write("\r\n");
      out.write("      </section>\r\n");
      out.write("      </header>\r\n");
      out.write("   </div>\r\n");
      out.write("   </div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("/* html { font-size: calc(1em + 1vw) } */\r\n");
      out.write("body, div, dl, dt, dd, h1, h2, h3, h4, h5, h6, pre, legend, \r\n");
      out.write("p, form, fieldset, input, textarea, select, blockquote, th, td { font-family: 'Nanum Gothic', sans-serif !important; line-height: 1.5; }\r\n");
      out.write("\r\n");
      out.write(".nav { display: flex; align: center; width: 100%; height:50px; }\r\n");
      out.write(".nav .gnb {  margin : auto; }\r\n");
      out.write(".nav .gnb li {display: inline-block; font-size: 17px; font-weight: 600; }\r\n");
      out.write(".nav .gnb li a { display: block; color: #272727; text-align: center; padding: 0 50px; line-height: 50px; height: 50px; text-decoration: none; }\r\n");
      out.write("\r\n");
      out.write("/* .nav .gnb .dropbtn {width: 40px;} */\r\n");
      out.write(".nav .gnb .dropbtn:hover {color: #fff; background: #0071bc}\r\n");
      out.write("\r\n");
      out.write(".nav .gnb .dropdown-content { display: none; align: center; position: absolute; width: 100%; max-width: 180px; z-index: 9000; }\r\n");
      out.write(".nav .gnb .dropdown-content a { color: #265277; padding: 0px 20px; text-decoration: none; display: block; align: center; text-align: center; font-size: 14px; background: rgba(255,255,255, 0.94);}\r\n");
      out.write(".nav .gnb .dropdown-content a:first-child { border-top: none; }\r\n");
      out.write(".nav .gnb .dropdown:hover .dropdown-content { display: block; align: center;}\r\n");
      out.write(".nav .gnb .dropdown-content a:hover {color: #fff; background: #0071bc}}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"nav\">\r\n");
      out.write("\t\t\t\t<ul class=\"gnb\">\r\n");
      out.write("\t\t\t\t\t<li class=\"dropdown\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"/jiksan/views/about/about-clinic.jsp\" class=\"dropbtn\">병원안내</a>\r\n");
      out.write("\t\t\t\t\t\t<div  class=\"dropdown-content\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"/jiksan/views/about/about-services.jsp\">진료안내</a>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"/jiksan/views/about/about-team.jsp\">의료진 소개</a>\r\n");
      out.write("                            <a href=\"/jiksan/views/about/contact-us.jsp\">오시는길</a>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<li class=\"dropdown\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"/jiksan/disease?disease_no=108\" class=\"dropbtn\">당뇨클리닉</a>\r\n");
      out.write("\t\t\t\t\t\t<div  class=\"dropdown-content\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"/jiksan/disease?disease_no=108\" >당뇨병이란?</a>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"/jiksan/views/diabetes/diabetes-diet.jsp\" >당뇨병과 식생활</a>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"/jiksan/views/diabetes/diabetes-exercise.jsp\" >당뇨병과 운동</a>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"/jiksan/views/diabetes/diabetes-complications.jsp\" >당뇨병 합병증</a>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<li class=\"dropdown\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"/jiksan/dlist\"  class=\"dropbtn\">건강정보</a>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"dropdown-content\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"/jiksan/dlist\">질환백과</a>\r\n");
      out.write("\t\t\t\t\t\t\t");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<li class=\"dropdown\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"/jiksan/views/reservation/about-appt.jsp\"  class=\"dropbtn\">진료 예약</a>\r\n");
      out.write("\t\t\t\t\t\t<div  class=\"dropdown-content\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"/jiksan/views/reservation/about-appt.jsp\">예약안내</a>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"/jiksan/reservation\">진료 예약하기</a>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<li class=\"dropdown\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"/jiksan/nlist\"  class=\"dropbtn\">커뮤니티</a>\r\n");
      out.write("\t\t\t\t\t\t<div  class=\"dropdown-content\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"/jiksan/nlist\">공지사항</a>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"/jiksan/faqlist\">자주묻는 질문</a>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"/jiksan/qalist\">Q&A 게시판</a>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("<div class=\"lnb\">    \r\n");
      out.write("\t<h2 class=\"lnb_title\">건강정보</h2>\t\t\r\n");
      out.write("\t<ul class=\"lnb_menu\">\r\n");
      out.write("\t\t<li class=\"on\"><a href=\"#\">질환백과</a></li>\r\n");
      out.write("\t\t<li><a href=\"/jiksan/views/common/error.jsp\">최근 환자 분석</a></li>\r\n");
      out.write("\t</ul>            \r\n");
      out.write("\t<div class=\"lnb_box01\">\r\n");
      out.write("\t\t<dl class=\"lnb_txt01\">\r\n");
      out.write("\t\t\t<dt><b>직산 가정의학과 의원</b></dt>\r\n");
      out.write("\t\t</dl>\r\n");
      out.write("\t\t<p class=\"num\">041-573-5595</p>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"lnb_box02\">\r\n");
      out.write("\t\t<p class=\"num02\"><span>평일</span> 08:30 ~ 18:00</p>\r\n");
      out.write("\t\t<p class=\"num02\"><span>토요일</span> 09:00 ~ 13:00</p>\r\n");
      out.write("\t\t<p class=\"num02\"><span>점심시간</span> 13:00 ~ 14:00</p>\r\n");
      out.write("\t\t<p class=\"time_comment\">화요일 야간진료는 21:00 까지이며, <br>일요일/공휴일은 휴무입니다.</p>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<hr id=\"floatClear\">\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"diseaseContents\">\r\n");
      out.write("\r\n");
      out.write("<h1 align=\"center\" >질환백과</h1>\r\n");
      out.write("<br>\r\n");
      out.write("   <form align=\"center\" action=\"/jiksan/dsearch\" method=\"post\">\r\n");
      out.write("      <select name=\"category\">\r\n");
      out.write("      \t\t<option value= \"diseaseNm\">전체 검색</option>\r\n");
      out.write("      \t\t<option value=\"diseaseNm\" selected>질환 및 질병</option>\r\n");
      out.write("      \t\t<option value=\"diseaseNm\">검사 및 치료</option>\r\n");
      out.write("      </select>\r\n");
      out.write("      <input type=\"search\" name=\"keyword\" size=40px; placeholder=\"검색어 입력\">\r\n");
      out.write("      <input type=\"submit\" value=\"검색\" >\r\n");
      out.write("   </form>\r\n");
      out.write("   <br><br>\r\n");
      out.write("   \r\n");
      out.write("<!-- <table align=\"center\" width=\"500\" border=\"1\" cellspacing=\"0\" cellpadding=\"1\">\r\n");
      out.write("<tr><th>번호</th><th>제목</th><th>(썸네일이 올자리)</th></tr> -->\r\n");
 for(Disease d : list){ 
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t");
      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<button type=\"submit\" onclick=\"location.href='disease?disease_no=");
      out.print(d.getDiseaseNo());
      out.write("'\"\r\n");
      out.write("\t\t\tstyle=\"width: 150px; height: 150px;\">");
      out.print( d.getDiseaseNm() );
      out.write("</button>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write('\r');
      out.write('\n');
 } //for each 
      out.write("\r\n");
      out.write("<!-- </table> -->\r\n");
      out.write("\r\n");
      out.write('\r');
      out.write('\n');
 if(keyword == null){ 
      out.write("\r\n");
      out.write("<div style=\"text-align: center;\">\r\n");
  if(currentPage <= 1){  
      out.write("\r\n");
      out.write("[맨처음]\r\n");
}else{ 
      out.write("\r\n");
      out.write("<a href=\"/jiksan/dlist?page=1\">[맨처음]</a>\r\n");
 }  
      out.write(" &nbsp;\r\n");
      out.write("\r\n");
  if((currentPage-10) < startPage && (currentPage - 10) >= 1){  
      out.write("\r\n");
      out.write("<a href=\"/jiksan/dlist?page=");
      out.print( startPage-10 );
      out.write("\">[이전]</a>\r\n");
}else{ 
      out.write("\r\n");
      out.write("[이전]\r\n");
 }  
      out.write(" &nbsp;\r\n");
      out.write("\r\n");
      out.write("\r\n");
 for(int p = startPage; p <= endPage; p++){
				if(p == currentPage){	

      out.write("\r\n");
      out.write("<font size=\"4\" color=\"red\">[");
      out.print( p  );
      out.write("]</font>\r\n");
 }else{ 
      out.write("\r\n");
      out.write("<a href=\"/jiksan/dlist?page=");
      out.print( p );
      out.write('"');
      out.write('>');
      out.print( p  );
      out.write("</a>\r\n");
 }
		} 
      out.write(" &nbsp;\r\n");
      out.write("\r\n");
  if((currentPage+10) > endPage && (currentPage + 10) < maxPage){  
      out.write("\r\n");
      out.write("<a href=\"/jiksan/dlist?page=");
      out.print( startPage+10 );
      out.write("\">[다음]</a>\r\n");
}else{ 
      out.write("\r\n");
      out.write("[다음]\r\n");
 }  
      out.write(" &nbsp;\r\n");
      out.write("\r\n");
      out.write("\r\n");
  if(currentPage >= maxPage){  
      out.write("\r\n");
      out.write("[맨끝]\r\n");
}else{ 
      out.write("\r\n");
      out.write("<a href=\"/jiksan/dlist?page=");
      out.print( maxPage );
      out.write("\">[맨끝]</a>\r\n");
 }  
      out.write("\r\n");
      out.write("&nbsp;\r\n");
}else{ 
      out.write("\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div style=\"text-align: center;\">\r\n");
  if(currentPage <= 1){  
      out.write("\r\n");
      out.write("[맨처음]\r\n");
}else{ 
      out.write("\r\n");
      out.write("<a href=\"/jiksan/dsearch?page=1&category=");
      out.print( category );
      out.write("&keyword=");
      out.print( keyword );
      out.write("\">[맨처음]</a>\r\n");
 }  
      out.write(" &nbsp;\r\n");
      out.write("\r\n");
  if((currentPage-10) < startPage && (currentPage - 10) >= 1){  
      out.write("\r\n");
      out.write("<a href=\"/jiksan/dsearch?page=");
      out.print( startPage-10 );
      out.write("&category=");
      out.print( category );
      out.write("&keyword=");
      out.print( keyword );
      out.write("\">[이전]</a>\r\n");
}else{ 
      out.write("\r\n");
      out.write("[이전]\r\n");
 }  
      out.write(" &nbsp;\r\n");
      out.write("\r\n");
      out.write("\r\n");
 for(int p = startPage; p <= endPage; p++){
				if(p == currentPage){	

      out.write("\r\n");
      out.write("<font size=\"4\" color=\"red\">[");
      out.print( p  );
      out.write("]</font>\r\n");
 }else{ 
      out.write("\r\n");
      out.write("<a href=\"/jiksan/dsearch?page=");
      out.print( p );
      out.write("&category=");
      out.print( category );
      out.write("&keyword=");
      out.print( keyword );
      out.write('"');
      out.write('>');
      out.print( p  );
      out.write("</a>\r\n");
      out.write("\r\n");
 }
		} 
      out.write(" &nbsp;\r\n");
      out.write("\r\n");
  if((currentPage+10) > endPage && (currentPage + 10) < maxPage){  
      out.write("\r\n");
      out.write("<a href=\"/jiksan/dsearch?page=");
      out.print( startPage+10 );
      out.write("&category=");
      out.print( category );
      out.write("&keyword=");
      out.print( keyword );
      out.write("\">[다음]</a>\r\n");
}else{ 
      out.write("\r\n");
      out.write("[다음]\r\n");
 }  
      out.write(" &nbsp;\r\n");
      out.write("\r\n");
      out.write("\r\n");
  if(currentPage >= maxPage){  
      out.write("\r\n");
      out.write("[맨끝]\r\n");
}else{ 
      out.write("\r\n");
      out.write("<a href=\"/jiksan/dsearch?page=");
      out.print( maxPage );
      out.write("&category=");
      out.print( category );
      out.write("&keyword=");
      out.print( keyword );
      out.write("\">[맨끝]</a>\r\n");
 }  
      out.write("\r\n");
      out.write("&nbsp;\r\n");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("footer {\r\n");
      out.write("\tbackground:#3e4247;\r\n");
      out.write("\ttext-align : center;\r\n");
      out.write("\twidth : 100%;\r\n");
      out.write("\theight : 10%;\r\n");
      out.write("\tcolor: #d1d1d1;\r\n");
      out.write("\tfont-size : 0.8em;\r\n");
      out.write("\tpadding-top : 2%;\t\r\n");
      out.write("\tpadding-bottom : 2%;\t\r\n");
      out.write("\tline-height:1;\r\n");
      out.write("}\r\n");
      out.write("footer div h3 {\r\n");
      out.write("\tcolor: #fff;\r\n");
      out.write("\tfont-size : 1.2em;\r\n");
      out.write("\tfont-weight : none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".footer_btn_list li {\r\n");
      out.write(" float: auto; overflow: hidden;\r\n");
      out.write(" padding-right: 10px;\r\n");
      out.write(" display:inline;\r\n");
      out.write(" line-height:2;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#copyright, .footer_btn_list, address{\r\n");
      out.write("\tcolor: #9AA0A6 /* #80868B */\r\n");
      out.write("} \r\n");
      out.write("hr { clear : both; }\r\n");
      out.write("</style>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\t//개인정보처리방침\r\n");
      out.write("\tfunction OpenMemberPrivate() { // \"개인정보처리방침\" 만들기? 가져오기\r\n");
      out.write("\t\twindow.open(\r\n");
      out.write("\t\t\t\t\t\t\"/jiksan/resources/js/개인정보처리방침.asp\",\r\n");
      out.write("\t\t\t\t\t\t\"MemberPrivate\",\r\n");
      out.write("\t\t\t\t\t\t\"toolbar=0, left=100, top=50, location=0, directories=0, status=0, menubar=0, scrollbars=1, resizable=0, copyhistory=0, width=600 ,height=600\");\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<footer>\r\n");
      out.write("<div>\r\n");
      out.write("\t\t\t\t<h3><a href=\"/jiksan/index.jsp\" style=\"font-weight:500;\">직산 가정의학과 의원 Jiksan Family Medicine Clinic</a></h3><br>\r\n");
      out.write("\t\t\t\t<address>충남 천안시 서북구 직산읍 직산로 31 직산농협 2층 &nbsp;&nbsp;&nbsp;&nbsp; (041) 583-8500\r\n");
      out.write("\t\t\t\t</address>\r\n");
      out.write("\t\t\t\t<br> <br>\r\n");
      out.write("\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t평일 08:30 ~ 18:00 &nbsp;&nbsp;&nbsp;&nbsp; 토요일 09:00 ~ 13:00\r\n");
      out.write("\t\t\t\t\t&nbsp;&nbsp;&nbsp;&nbsp; 점심시간 13:00 ~ 14:00\r\n");
      out.write("\t\t\t\t\t&nbsp;&nbsp;&nbsp;&nbsp; 화요일 야간진료 21:00 까지 &nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t\t<i>일요일/공휴일은 휴무입니다.</i>\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t<label id=\"copyright\">Copyright ⓒ 2020 by Jiksan Family Medicine Clinic. All rights reserved.</label>\r\n");
      out.write("\t\t\t\t<br>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\t<ul class=\"footer_btn_list\">\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\" onclick=\"OpenMemberPrivate();\" style=\"cursor: pointer;\">개인정보처리방침</a></li>\r\n");
      out.write("\t\t\t\t\t<li> | </li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">이용약관</a></li>\r\n");
      out.write("\t\t\t\t\t<li> | </li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"/jiksan/views/about/contact-us.jsp\">찾아오시는길</a></li>\t\t\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("</footer>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
